#!/bin/bash
# Build "Salat Time.app" — menu-bar prayer-times app with live countdown,
# adhan audio catalog, and native notifications.
set -e
cd "$(dirname "$0")"

BINARY="AwqatSalat"
APP_NAME="Salat Time"
APP_DIR="$APP_NAME.app"
CONTENTS="$APP_DIR/Contents"
MACOS_DIR="$CONTENTS/MacOS"
RESOURCES_DIR="$CONTENTS/Resources"

# ---------- clean & scaffold ------------------------------------------------
rm -rf "$APP_DIR"
mkdir -p "$MACOS_DIR" "$RESOURCES_DIR"

# ---------- compile Swift (main app) ---------------------------------------
echo "Compiling main app..."
swiftc main.swift \
    -o "$MACOS_DIR/$BINARY" \
    -framework Cocoa \
    -framework WebKit \
    -framework AVFoundation \
    -framework CoreLocation \
    -framework UserNotifications \
    -framework ServiceManagement

# ---------- multi-res icns --------------------------------------------------
echo "Building icon..."
ICONSET="AppIcon.iconset"
rm -rf "$ICONSET"; mkdir "$ICONSET"
for sz in 16 32 128 256 512; do
    sips -z "$sz" "$sz" icon.png --out "$ICONSET/icon_${sz}x${sz}.png" > /dev/null
    sips -z $((sz*2)) $((sz*2)) icon.png --out "$ICONSET/icon_${sz}x${sz}@2x.png" > /dev/null
done
iconutil -c icns "$ICONSET" -o "$RESOURCES_DIR/AppIcon.icns"
rm -rf "$ICONSET"

# Also copy the raw icon for in-app header display
cp icon.png "$RESOURCES_DIR/icon.png"

# ---------- adhan audio catalog --------------------------------------------
# 14 hand-picked adhans sourced from assabile.com's curated collection.
# Each file's reciter/mosque was identified via its ID3 tags. Assabile
# enforces a Referer check on its media CDN, so we pass one when fetching.
echo "Fetching adhan audio catalog..."
ASSABILE_BASE="https://media.assabile.com/assabile/adhan_3435370"
ASSABILE_UA="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15"
download_adhan_assabile () {
    local fname="$1"
    local hash="$2"
    local out="$RESOURCES_DIR/$fname"
    local url="$ASSABILE_BASE/$hash.mp3"
    if curl -sSfL --max-time 45 \
            -H "Referer: https://www.assabile.com/" \
            -A "$ASSABILE_UA" \
            -o "$out" "$url"; then
        local size=$(stat -f%z "$out" 2>/dev/null || echo 0)
        if [ "$size" -gt 20000 ]; then
            echo "  $fname  ($size bytes)"
            return 0
        fi
    fi
    rm -f "$out"
    echo "  ($fname skipped)"
    return 1
}

# Download all 14 adhans. IDs are short, stable, and match the adhanCatalog
# in main.swift. Ordered by popularity/recognizability — the three mosque
# recordings (Makkah, Madinah, Al-Aqsa) lead, followed by major reciters.
download_adhan_assabile "adhan_makkah_mulla.mp3"  "166d1f7c435a"  # Makkah — Sheikh Ali Ibn Ahmed Mala
download_adhan_assabile "adhan_madinah.mp3"       "b30ca9a3e115"  # Madinah — Masjid an-Nabawi
download_adhan_assabile "adhan_aqsa.mp3"          "768559b47c2e"  # Al-Aqsa — Naji Qazzaz
download_adhan_assabile "adhan_dossari.mp3"       "f5370aa1a7e2"  # Yasser Al-Dossari (Saudi Arabia)
download_adhan_assabile "adhan_zahrani.mp3"       "cb51ad2c0c7e"  # Mansour Al-Zahrani
download_adhan_assabile "adhan_obaid.mp3"         "45299e6a8a68"  # Nasser Al-Obaid
download_adhan_assabile "adhan_majali.mp3"        "495dea4f4ea5"  # Hamza Al-Majali
download_adhan_assabile "adhan_yamani.mp3"        "091fa01b11f4"  # Wadi' Hammadi Al-Yamani
download_adhan_assabile "adhan_kabbara.mp3"       "8bd66fa73ff9"  # Mohammed Salahuddin Kabbara
download_adhan_assabile "adhan_kourdi.mp3"        "8c052a5edec1"  # Ahmed Al-Kourdi
download_adhan_assabile "adhan_feqy.mp3"          "83e17f5db5a7"  # Mohamed Abdel-Basset Al-Feqy
download_adhan_assabile "adhan_damradach.mp3"     "cd17c7200df5"  # Mohammed Al-Damradach
download_adhan_assabile "adhan_kreiny.mp3"        "229d65e40fdf"  # Mohammed Al-Kreiny Al-Malouki
download_adhan_assabile "adhan_jazairi.mp3"       "0bf83c80b583"  # Rabih Ibn Darah Al-Jazairi (Algeria)

# Legacy filenames — any older install whose UserDefaults still references
# the old catalog entries ("adhan.mp3", "adhan_makkah.mp3", etc.) gets
# redirected to the new Makkah recording so the app never fails to load
# a sound on first launch after upgrading.
if [ -f "$RESOURCES_DIR/adhan_makkah_mulla.mp3" ]; then
    [ ! -f "$RESOURCES_DIR/adhan.mp3" ]         && cp "$RESOURCES_DIR/adhan_makkah_mulla.mp3" "$RESOURCES_DIR/adhan.mp3"
    [ ! -f "$RESOURCES_DIR/adhan_makkah.mp3" ]  && cp "$RESOURCES_DIR/adhan_makkah_mulla.mp3" "$RESOURCES_DIR/adhan_makkah.mp3"
    [ ! -f "$RESOURCES_DIR/adhan_madina.mp3" ]  && cp "$RESOURCES_DIR/adhan_makkah_mulla.mp3" "$RESOURCES_DIR/adhan_madina.mp3"
fi

# ---------- Cairo fonts (Arabic UI) ----------------------------------------
echo "Fetching Cairo fonts..."
download_font () {
    local fname="$1"
    local url="$2"
    local out="$RESOURCES_DIR/$fname"
    if curl -sSfL --max-time 30 -o "$out" "$url"; then
        local size=$(stat -f%z "$out" 2>/dev/null || echo 0)
        if [ "$size" -gt 10000 ]; then
            echo "  $fname  ($size bytes)"
            return 0
        fi
    fi
    rm -f "$out"
    return 1
}

# Google Fonts removed the /static per-weight files in 2024 — only a single
# variable font remains at the top of the Cairo folder. macOS + Swift can use
# a variable font just fine; we register it once and ask NSFontManager for the
# weight we want at render time (see `Localizer.font(size:weight:)`).
# The filename contains "[slnt,wght]" which needs URL-encoding in the path.
download_font "Cairo-Variable.ttf" \
    "https://raw.githubusercontent.com/google/fonts/main/ofl/cairo/Cairo%5Bslnt%2Cwght%5D.ttf" \
    || echo "  (Cairo-Variable skipped)"

# ---------- adhkar audio + data (morning/evening) --------------------------
# 27 per-dhikr MP3s sourced from hisnmuslim.com (Hisn al-Muslim) and
# mp3quran.net (Mishary Al-Afasy for the Qur'anic adhkar — Ayatul Kursi
# and the three Quls). Each file is one dhikr recitation; the app plays
# them in order and shows the matching Arabic text in the floating window.
echo "Fetching adhkar audio..."
ADHKAR_AUDIO_SUBDIR="adhkar_audio"
mkdir -p "$RESOURCES_DIR/$ADHKAR_AUDIO_SUBDIR"
download_adhkar () {
    local fname="$1"
    local url="$2"
    local out="$RESOURCES_DIR/$ADHKAR_AUDIO_SUBDIR/$fname"
    # Skip if already downloaded (cached from a previous build)
    if [ -s "$out" ]; then
        local sz=$(stat -f%z "$out" 2>/dev/null || echo 0)
        [ "$sz" -gt 10000 ] && return 0
    fi
    if curl -sSfL --max-time 45 -A "Mozilla/5.0" -o "$out" "$url"; then
        local size=$(stat -f%z "$out" 2>/dev/null || echo 0)
        if [ "$size" -gt 10000 ]; then
            echo "  $fname  ($size bytes)"
            return 0
        fi
    fi
    rm -f "$out"
    echo "  (failed: $fname)"
    return 1
}

# hisnmuslim.com hosts most adhkar; mp3quran.net (Mishary Al-Afasy) hosts
# the three Quls (112/113/114) used as both morning and evening adhkar.
download_adhkar "75.mp3"   "https://www.hisnmuslim.com/audio/ar/75.mp3"
download_adhkar "77.mp3"   "https://www.hisnmuslim.com/audio/ar/77.mp3"
download_adhkar "78.mp3"   "https://www.hisnmuslim.com/audio/ar/78.mp3"
download_adhkar "79.mp3"   "https://www.hisnmuslim.com/audio/ar/79.mp3"
download_adhkar "80.mp3"   "https://www.hisnmuslim.com/audio/ar/80.mp3"
download_adhkar "81.mp3"   "https://www.hisnmuslim.com/audio/ar/81.mp3"
download_adhkar "82.mp3"   "https://www.hisnmuslim.com/audio/ar/82.mp3"
download_adhkar "83.mp3"   "https://www.hisnmuslim.com/audio/ar/83.mp3"
download_adhkar "84.mp3"   "https://www.hisnmuslim.com/audio/ar/84.mp3"
download_adhkar "85.mp3"   "https://www.hisnmuslim.com/audio/ar/85.mp3"
download_adhkar "86.mp3"   "https://www.hisnmuslim.com/audio/ar/86.mp3"
download_adhkar "87.mp3"   "https://www.hisnmuslim.com/audio/ar/87.mp3"
download_adhkar "88.mp3"   "https://www.hisnmuslim.com/audio/ar/88.mp3"
download_adhkar "89.mp3"   "https://www.hisnmuslim.com/audio/ar/89.mp3"
download_adhkar "90.mp3"   "https://www.hisnmuslim.com/audio/ar/90.mp3"
download_adhkar "91.mp3"   "https://www.hisnmuslim.com/audio/ar/91.mp3"
download_adhkar "92.mp3"   "https://www.hisnmuslim.com/audio/ar/92.mp3"
download_adhkar "93.mp3"   "https://www.hisnmuslim.com/audio/ar/93.mp3"
download_adhkar "94.mp3"   "https://www.hisnmuslim.com/audio/ar/94.mp3"
download_adhkar "95.mp3"   "https://www.hisnmuslim.com/audio/ar/95.mp3"
download_adhkar "96.mp3"   "https://www.hisnmuslim.com/audio/ar/96.mp3"
download_adhkar "97.mp3"   "https://www.hisnmuslim.com/audio/ar/97.mp3"
download_adhkar "98.mp3"   "https://www.hisnmuslim.com/audio/ar/98.mp3"
download_adhkar "101.mp3"  "https://www.hisnmuslim.com/audio/ar/101.mp3"
download_adhkar "112.mp3"  "https://server8.mp3quran.net/afs/112.mp3"
download_adhkar "113.mp3"  "https://server8.mp3quran.net/afs/113.mp3"
download_adhkar "114.mp3"  "https://server8.mp3quran.net/afs/114.mp3"

# Bundle the adhkar text/metadata (morning + evening sets, sourced from
# the open-source Morning and Evening Adhkar DB / Hisn al-Muslim).
cp adhkar.json "$RESOURCES_DIR/adhkar.json"

# ---------- translations.json (i18n) ---------------------------------------
echo "Writing translations.json..."
cat > "$RESOURCES_DIR/translations.json" <<'JSON_EOF'
{
  "en": {
    "col.prayer": "Prayer",
    "col.adhan": "Adhan",
    "col.iqama": "Iqama",
    "prayer.fajr": "Fajr",
    "prayer.shuruq": "Shuruq",
    "prayer.dhuhr": "Dhuhr",
    "prayer.asr": "Asr",
    "prayer.maghrib": "Maghrib",
    "prayer.isha": "Isha",
    "label.jumua": "Jumu'ah",
    "label.next_prayer": "Next prayer",
    "tooltip.refresh": "Refresh",
    "tooltip.language": "Change language",
    "tooltip.theme": "Theme",
    "menu.theme.header.appearance": "Appearance",
    "menu.theme.appearance.system": "System",
    "menu.theme.appearance.light": "Light",
    "menu.theme.appearance.dark": "Dark",
    "menu.theme.header.accent": "Accent color",
    "menu.theme.accent.green": "Green",
    "menu.theme.accent.blue": "Blue",
    "menu.theme.accent.purple": "Purple",
    "menu.theme.accent.orange": "Orange",
    "menu.theme.accent.red": "Red",
    "menu.theme.accent.teal": "Teal",
    "menu.theme.header.material": "Background",
    "menu.theme.material.opaque": "Opaque",
    "menu.theme.material.glass": "Liquid Glass",
    "tooltip.change": "Change mosque",
    "tooltip.settings": "Settings",
    "tooltip.back": "Back",
    "tooltip.test_adhan": "Test adhan",
    "tooltip.stop_adhan": "Stop adhan",
    "menubar.stop_adhan": "Stop the adhan",
    "mosque.default": "Mosque",
    "menu.open": "Open Salat Time",
    "menu.refresh": "Refresh",
    "menu.choose": "Choose Mosque…",
    "menu.settings": "Settings…",
    "menu.favorites": "Favorites",
    "menu.quit": "Quit",
    "settings.title": "Settings",
    "settings.section.language": "Language",
    "settings.section.appearance": "Appearance",
    "settings.section.accent": "Accent color",
    "settings.section.material": "Material",
    "settings.section.adhan": "Adhan",
    "settings.section.notifications": "Notifications",
    "settings.section.mosque": "Mosque",
    "settings.appearance.system": "System",
    "settings.appearance.light": "Light",
    "settings.appearance.dark": "Dark",
    "settings.adhan.play": "Play adhan sound",
    "settings.adhan.sound": "Sound",
    "settings.adhan.output": "Output",
    "settings.adhan.output.default": "System default",
    "settings.notif.show": "Show notifications",
    "settings.notif.headsup": "Heads-up before prayer",
    "settings.notif.headsup.off": "Off",
    "settings.notif.headsup.minutes": "%d min before",
    "settings.notif.headsup.title": "%@ in %d min",
    "settings.mosque.currently": "Currently",
    "settings.mosque.none": "None selected",
    "settings.mosque.change": "Change mosque",
    "settings.section.time_format": "Time format",
    "settings.time_format.24h": "24-hour",
    "settings.time_format.12h": "12-hour",
    "settings.section.menu_bar": "Menu bar",
    "settings.bar.icon": "Icon",
    "settings.bar.time": "Scheduled time",
    "settings.bar.countdown": "Countdown",
    "settings.bar.hijri": "Hijri date",
    "settings.bar.hijri.format.off": "Off",
    "settings.bar.hijri.format.full": "Full (15 Shawwāl 1447)",
    "settings.bar.hijri.format.daymonth": "Day + month (15 Shawwāl)",
    "settings.bar.hijri.format.month": "Month only (Shawwāl)",
    "settings.bar.hijri.format.day": "Day only (15)",
    "settings.save": "Save",
    "settings.quit": "Quit",
    "header.openMosque": "Open mosque page on mawaqit.net",
    "picker.title": "Choose a mosque",
    "picker.btn.search": "Search",
    "picker.btn.add": "Add",
    "picker.btn.near": "Nearby",
    "picker.tab.favorites": "Favorites",
    "picker.tab.search": "Search",
    "picker.tab.near": "Nearby",
    "picker.tab.url": "Add by URL",
    "picker.placeholder.search": "Search city or mosque",
    "picker.placeholder.city": "Your city",
    "settings.tab.mosque": "Mosque",
    "settings.tab.appearance": "Appearance",
    "settings.tab.menu_bar": "Menu bar",
    "settings.tab.sound": "Sound",
    "settings.section.startup": "Startup",
    "settings.startup.open_at_login": "Open at login",
    "tooltip.open_at_login_failed": "macOS refused the login-item registration. Try again or enable it in System Settings → General → Login Items.",
    "picker.tooltip.remove_fav": "Remove from favorites",
    "picker.tooltip.saved": "Saved to favorites",
    "picker.tooltip.add_fav": "Add to favorites",
    "picker.tooltip.is_default": "Current default",
    "picker.tooltip.set_default": "Set as default",
    "picker.status.set_default_prefix": "Set default:",
    "picker.status.added_fav_prefix": "Added to favorites:",
    "picker.status.removed_fav_prefix": "Removed from favorites:",
    "menu.adhkar": "Adhkar",
    "adhkar.morning_title": "Adhkar of the Morning",
    "adhkar.evening_title": "Adhkar of the Evening",
    "adhkar.play": "Play",
    "adhkar.pause": "Pause",
    "adhkar.mute": "Mute",
    "adhkar.unmute": "Unmute",
    "adhkar.stop": "Stop",
    "adhkar.next": "Next dhikr",
    "adhkar.prev": "Previous dhikr",
    "settings.section.adhkar": "Adhkar",
    "settings.adhkar.auto": "Auto-recite morning & evening adhkar",
    "main.tab.prayer_times": "Prayer Times",
    "main.tab.adhkar": "Adhkar",
    "main.tab.adhan": "Adhan",
    "main.tab.settings": "Settings",
    "menu.main_window": "Open Main Window…",
    "adhkar.editor.coming_soon": "Adhkar editor — coming in the next build",
    "adhkar.editor.title": "Adhkar Collections",
    "adhkar.editor.collections": "Collections",
    "adhkar.editor.new_collection": "New Collection",
    "adhkar.editor.untitled": "Untitled",
    "adhkar.editor.items_in": "Items in \"%@\"",
    "adhkar.editor.add_from_library": "Add from Library…",
    "adhkar.editor.add_custom": "Add Custom…",
    "adhkar.editor.no_collection_selected": "Select a collection or create a new one.",
    "adhkar.editor.empty_collection": "This collection is empty. Add adhkar from the library or create your own.",
    "adhkar.editor.delete_collection": "Delete this collection?",
    "adhkar.editor.delete_collection_msg": "This cannot be undone.",
    "adhkar.editor.delete_item": "Remove this dhikr?",
    "adhkar.editor.repeat": "Repeat",
    "adhkar.editor.virtue": "Virtue / Notes",
    "adhkar.editor.source": "Source",
    "adhkar.editor.arabic": "Arabic Text",
    "adhkar.editor.audio": "Audio",
    "adhkar.editor.audio.choose": "Choose audio…",
    "adhkar.editor.audio.import": "Import file…",
    "adhkar.editor.audio.none": "None",
    "adhkar.editor.schedule": "Schedule",
    "adhkar.editor.schedule.manual": "Manual (no auto-play)",
    "adhkar.editor.schedule.shuruq": "At Sunrise (Shuruq)",
    "adhkar.editor.schedule.fajr": "After Fajr",
    "adhkar.editor.schedule.dhuhr": "After Dhuhr",
    "adhkar.editor.schedule.asr": "After Asr",
    "adhkar.editor.schedule.maghrib": "After Maghrib",
    "adhkar.editor.schedule.isha": "After Isha",
    "adhkar.editor.autoplay": "Auto-play at scheduled time",
    "adhkar.editor.save": "Save",
    "adhkar.editor.cancel": "Cancel",
    "adhkar.editor.library_title": "Add from Library",
    "adhkar.editor.library_pick": "Pick adhkar to add:",
    "adhkar.editor.library_add_selected": "Add Selected",
    "adhkar.editor.custom_title": "Add Custom Dhikr",
    "adhkar.editor.custom_hint": "Type or paste the Arabic text, then choose a repeat count and audio.",
    "adhkar.editor.move_up": "Move up",
    "adhkar.editor.move_down": "Move down",
    "adhkar.editor.remove": "Remove",
    "adhkar.editor.play_preview": "Preview audio",
    "adhkar.import_audio": "Import",
    "adhkar.editor.renamed": "Renamed",
    "adhkar.editor.count_times": "%d times"
  },
  "fr": {
    "col.prayer": "Prière",
    "col.adhan": "Adhan",
    "col.iqama": "Iqama",
    "prayer.fajr": "Fajr",
    "prayer.shuruq": "Shuruq",
    "prayer.dhuhr": "Dhouhr",
    "prayer.asr": "Asr",
    "prayer.maghrib": "Maghrib",
    "prayer.isha": "Isha",
    "label.jumua": "Jumu'a",
    "label.next_prayer": "Prochaine prière",
    "tooltip.refresh": "Actualiser",
    "tooltip.language": "Changer de langue",
    "tooltip.theme": "Thème",
    "menu.theme.header.appearance": "Apparence",
    "menu.theme.appearance.system": "Système",
    "menu.theme.appearance.light": "Clair",
    "menu.theme.appearance.dark": "Sombre",
    "menu.theme.header.accent": "Couleur d'accent",
    "menu.theme.accent.green": "Vert",
    "menu.theme.accent.blue": "Bleu",
    "menu.theme.accent.purple": "Violet",
    "menu.theme.accent.orange": "Orange",
    "menu.theme.accent.red": "Rouge",
    "menu.theme.accent.teal": "Sarcelle",
    "menu.theme.header.material": "Arrière-plan",
    "menu.theme.material.opaque": "Opaque",
    "menu.theme.material.glass": "Verre liquide",
    "tooltip.change": "Changer de mosquée",
    "tooltip.settings": "Réglages",
    "tooltip.back": "Retour",
    "tooltip.test_adhan": "Tester l'adhan",
    "tooltip.stop_adhan": "Arrêter l'adhan",
    "menubar.stop_adhan": "Arrêter l'adhan",
    "mosque.default": "Mosquée",
    "menu.open": "Ouvrir Salat Time",
    "menu.refresh": "Actualiser",
    "menu.choose": "Choisir une mosquée…",
    "menu.settings": "Réglages…",
    "menu.favorites": "Favoris",
    "menu.quit": "Quitter",
    "settings.title": "Réglages",
    "settings.section.language": "Langue",
    "settings.section.appearance": "Apparence",
    "settings.section.accent": "Couleur d'accent",
    "settings.section.material": "Matière",
    "settings.section.adhan": "Adhan",
    "settings.section.notifications": "Notifications",
    "settings.section.mosque": "Mosquée",
    "settings.appearance.system": "Système",
    "settings.appearance.light": "Clair",
    "settings.appearance.dark": "Sombre",
    "settings.adhan.play": "Jouer l'adhan",
    "settings.adhan.sound": "Son",
    "settings.adhan.output": "Sortie",
    "settings.adhan.output.default": "Par défaut",
    "settings.notif.show": "Afficher les notifications",
    "settings.notif.headsup": "Alerte avant la prière",
    "settings.notif.headsup.off": "Désactivée",
    "settings.notif.headsup.minutes": "%d min avant",
    "settings.notif.headsup.title": "%@ dans %d min",
    "settings.mosque.currently": "Actuellement",
    "settings.mosque.none": "Aucune sélectionnée",
    "settings.mosque.change": "Changer de mosquée",
    "settings.section.time_format": "Format de l'heure",
    "settings.time_format.24h": "24 h",
    "settings.time_format.12h": "12 h",
    "settings.section.menu_bar": "Barre de menu",
    "settings.bar.icon": "Icône",
    "settings.bar.time": "Heure prévue",
    "settings.bar.countdown": "Compte à rebours",
    "settings.bar.hijri": "Date hégire",
    "settings.bar.hijri.format.off": "Masquée",
    "settings.bar.hijri.format.full": "Complète (15 Shawwāl 1447)",
    "settings.bar.hijri.format.daymonth": "Jour + mois (15 Shawwāl)",
    "settings.bar.hijri.format.month": "Mois uniquement (Shawwāl)",
    "settings.bar.hijri.format.day": "Jour uniquement (15)",
    "settings.save": "Enregistrer",
    "settings.quit": "Quitter",
    "header.openMosque": "Ouvrir la page de la mosquée sur mawaqit.net",
    "picker.title": "Choisir une mosquée",
    "picker.btn.search": "Rechercher",
    "picker.btn.add": "Ajouter",
    "picker.btn.near": "À proximité",
    "picker.tab.favorites": "Favoris",
    "picker.tab.search": "Rechercher",
    "picker.tab.near": "À proximité",
    "picker.tab.url": "Ajouter par URL",
    "picker.placeholder.search": "Rechercher une ville ou mosquée",
    "picker.placeholder.city": "Votre ville",
    "settings.tab.mosque": "Mosquée",
    "settings.tab.appearance": "Apparence",
    "settings.tab.menu_bar": "Barre de menus",
    "settings.tab.sound": "Son",
    "settings.section.startup": "Démarrage",
    "settings.startup.open_at_login": "Ouvrir à la connexion",
    "tooltip.open_at_login_failed": "macOS a refusé l'enregistrement. Réessayez ou activez-le dans Réglages système → Général → Ouverture.",
    "picker.tooltip.remove_fav": "Retirer des favoris",
    "picker.tooltip.saved": "Enregistré",
    "picker.tooltip.add_fav": "Ajouter aux favoris",
    "picker.tooltip.is_default": "Mosquée actuelle",
    "picker.tooltip.set_default": "Définir par défaut",
    "picker.status.set_default_prefix": "Défini par défaut :",
    "picker.status.added_fav_prefix": "Ajouté aux favoris :",
    "picker.status.removed_fav_prefix": "Retiré des favoris :",
    "menu.adhkar": "Adhkār",
    "adhkar.morning_title": "Adhkār du Matin",
    "adhkar.evening_title": "Adhkār du Soir",
    "adhkar.play": "Lire",
    "adhkar.pause": "Pause",
    "adhkar.mute": "Couper le son",
    "adhkar.unmute": "Réactiver le son",
    "adhkar.stop": "Arrêter",
    "adhkar.next": "Dhikr suivant",
    "adhkar.prev": "Dhikr précédent",
    "settings.section.adhkar": "Adhkār",
    "settings.adhkar.auto": "Réciter automatiquement les adhkār du matin et du soir",
    "main.tab.prayer_times": "Heures de Prière",
    "main.tab.adhkar": "Adhkār",
    "main.tab.adhan": "Adhān",
    "main.tab.settings": "Réglages",
    "menu.main_window": "Ouvrir la fenêtre principale…",
    "adhkar.editor.coming_soon": "Éditeur d'adhkār — dans la prochaine version",
    "adhkar.editor.title": "Collections d'Adhkār",
    "adhkar.editor.collections": "Collections",
    "adhkar.editor.new_collection": "Nouvelle collection",
    "adhkar.editor.untitled": "Sans titre",
    "adhkar.editor.items_in": "Éléments dans « %@ »",
    "adhkar.editor.add_from_library": "Ajouter depuis la bibliothèque…",
    "adhkar.editor.add_custom": "Ajouter personnalisé…",
    "adhkar.editor.no_collection_selected": "Sélectionnez une collection ou créez-en une nouvelle.",
    "adhkar.editor.empty_collection": "Cette collection est vide. Ajoutez des adhkār depuis la bibliothèque ou créez les vôtres.",
    "adhkar.editor.delete_collection": "Supprimer cette collection ?",
    "adhkar.editor.delete_collection_msg": "Cette action est irréversible.",
    "adhkar.editor.delete_item": "Retirer ce dhikr ?",
    "adhkar.editor.repeat": "Répétition",
    "adhkar.editor.virtue": "Mérite / Notes",
    "adhkar.editor.source": "Source",
    "adhkar.editor.arabic": "Texte arabe",
    "adhkar.editor.audio": "Audio",
    "adhkar.editor.audio.choose": "Choisir l'audio…",
    "adhkar.editor.audio.import": "Importer un fichier…",
    "adhkar.editor.audio.none": "Aucun",
    "adhkar.editor.schedule": "Planification",
    "adhkar.editor.schedule.manual": "Manuel (pas d'auto-play)",
    "adhkar.editor.schedule.shuruq": "Au lever du soleil (Shurūq)",
    "adhkar.editor.schedule.fajr": "Après Fajr",
    "adhkar.editor.schedule.dhuhr": "Après Dhuhr",
    "adhkar.editor.schedule.asr": "Après Asr",
    "adhkar.editor.schedule.maghrib": "Après Maghrib",
    "adhkar.editor.schedule.isha": "Après Ishā",
    "adhkar.editor.autoplay": "Lecture auto à l'heure prévue",
    "adhkar.editor.save": "Enregistrer",
    "adhkar.editor.cancel": "Annuler",
    "adhkar.editor.library_title": "Ajouter depuis la bibliothèque",
    "adhkar.editor.library_pick": "Choisir les adhkār à ajouter :",
    "adhkar.editor.library_add_selected": "Ajouter la sélection",
    "adhkar.editor.custom_title": "Ajouter un dhikr personnalisé",
    "adhkar.editor.custom_hint": "Saisissez ou collez le texte arabe, puis choisissez un nombre de répétitions et un audio.",
    "adhkar.editor.move_up": "Monter",
    "adhkar.editor.move_down": "Descendre",
    "adhkar.editor.remove": "Retirer",
    "adhkar.editor.play_preview": "Prévisualiser l'audio",
    "adhkar.import_audio": "Importer",
    "adhkar.editor.renamed": "Renommé",
    "adhkar.editor.count_times": "%d fois"
  },
  "es": {
    "col.prayer": "Oración",
    "col.adhan": "Adhan",
    "col.iqama": "Iqama",
    "prayer.fajr": "Fajr",
    "prayer.shuruq": "Shuruq",
    "prayer.dhuhr": "Dhuhr",
    "prayer.asr": "Asr",
    "prayer.maghrib": "Maghrib",
    "prayer.isha": "Isha",
    "label.jumua": "Yumu'ah",
    "label.next_prayer": "Próxima oración",
    "tooltip.refresh": "Actualizar",
    "tooltip.language": "Cambiar idioma",
    "tooltip.theme": "Tema",
    "menu.theme.header.appearance": "Apariencia",
    "menu.theme.appearance.system": "Sistema",
    "menu.theme.appearance.light": "Claro",
    "menu.theme.appearance.dark": "Oscuro",
    "menu.theme.header.accent": "Color de acento",
    "menu.theme.accent.green": "Verde",
    "menu.theme.accent.blue": "Azul",
    "menu.theme.accent.purple": "Morado",
    "menu.theme.accent.orange": "Naranja",
    "menu.theme.accent.red": "Rojo",
    "menu.theme.accent.teal": "Verde azulado",
    "menu.theme.header.material": "Fondo",
    "menu.theme.material.opaque": "Opaco",
    "menu.theme.material.glass": "Vidrio líquido",
    "tooltip.change": "Cambiar mezquita",
    "tooltip.settings": "Ajustes",
    "tooltip.back": "Atrás",
    "tooltip.test_adhan": "Probar adhan",
    "tooltip.stop_adhan": "Detener adhan",
    "mosque.default": "Mezquita",
    "menu.open": "Abrir Salat Time",
    "menu.refresh": "Actualizar",
    "menu.choose": "Elegir mezquita…",
    "menu.settings": "Ajustes…",
    "menu.favorites": "Favoritos",
    "menu.quit": "Salir",
    "settings.title": "Ajustes",
    "settings.section.language": "Idioma",
    "settings.section.appearance": "Apariencia",
    "settings.section.accent": "Color de acento",
    "settings.section.material": "Material",
    "settings.section.adhan": "Adhan",
    "settings.section.notifications": "Notificaciones",
    "settings.section.mosque": "Mezquita",
    "settings.appearance.system": "Sistema",
    "settings.appearance.light": "Claro",
    "settings.appearance.dark": "Oscuro",
    "settings.adhan.play": "Reproducir adhan",
    "settings.adhan.sound": "Sonido",
    "settings.adhan.output": "Salida",
    "settings.adhan.output.default": "Predeterminada",
    "settings.notif.show": "Mostrar notificaciones",
    "settings.mosque.currently": "Actualmente",
    "settings.mosque.none": "Ninguna seleccionada",
    "settings.mosque.change": "Cambiar mezquita",
    "settings.section.time_format": "Formato de hora",
    "settings.time_format.24h": "24 h",
    "settings.time_format.12h": "12 h",
    "settings.section.menu_bar": "Barra de menú",
    "settings.bar.icon": "Icono",
    "settings.bar.time": "Hora programada",
    "settings.bar.countdown": "Cuenta atrás",
    "settings.bar.hijri": "Fecha hégira",
    "settings.bar.hijri.format.off": "Desactivada",
    "settings.bar.hijri.format.full": "Completa (15 Shawwāl 1447)",
    "settings.bar.hijri.format.daymonth": "Día + mes (15 Shawwāl)",
    "settings.bar.hijri.format.month": "Solo mes (Shawwāl)",
    "settings.bar.hijri.format.day": "Solo día (15)",
    "settings.save": "Guardar",
    "settings.quit": "Salir",
    "header.openMosque": "Abrir página de la mezquita en mawaqit.net",
    "picker.title": "Elegir mezquita",
    "picker.btn.search": "Buscar",
    "picker.btn.add": "Añadir",
    "picker.btn.near": "Cercanas",
    "picker.tab.favorites": "Favoritos",
    "picker.tab.search": "Buscar",
    "picker.tab.near": "Cercanas",
    "picker.tab.url": "Añadir por URL",
    "picker.placeholder.search": "Buscar ciudad o mezquita",
    "picker.placeholder.city": "Tu ciudad",
    "settings.tab.mosque": "Mezquita",
    "settings.tab.appearance": "Apariencia",
    "settings.tab.menu_bar": "Barra de menús",
    "settings.tab.sound": "Sonido",
    "settings.section.startup": "Inicio",
    "settings.startup.open_at_login": "Abrir al iniciar sesión",
    "tooltip.open_at_login_failed": "macOS rechazó el registro. Intente de nuevo o actívelo en Configuración → General → Ítems de inicio.",
    "picker.tooltip.remove_fav": "Quitar de favoritos",
    "picker.tooltip.saved": "Guardado en favoritos",
    "picker.tooltip.add_fav": "Añadir a favoritos",
    "picker.tooltip.is_default": "Mezquita actual",
    "picker.tooltip.set_default": "Establecer como predeterminada",
    "picker.status.set_default_prefix": "Predeterminada:",
    "picker.status.added_fav_prefix": "Añadido a favoritos:",
    "picker.status.removed_fav_prefix": "Quitado de favoritos:",
    "menu.adhkar": "Adhkār",
    "adhkar.morning_title": "Adhkār de la Mañana",
    "adhkar.evening_title": "Adhkār de la Tarde",
    "adhkar.play": "Reproducir",
    "adhkar.pause": "Pausa",
    "adhkar.mute": "Silenciar",
    "adhkar.unmute": "Activar sonido",
    "adhkar.stop": "Detener",
    "adhkar.next": "Dhikr siguiente",
    "adhkar.prev": "Dhikr anterior",
    "settings.section.adhkar": "Adhkār",
    "settings.adhkar.auto": "Recitar automáticamente los adhkār de la mañana y la tarde",
    "main.tab.prayer_times": "Horarios de Oración",
    "main.tab.adhkar": "Adhkār",
    "main.tab.adhan": "Adhān",
    "main.tab.settings": "Ajustes",
    "menu.main_window": "Abrir ventana principal…",
    "adhkar.editor.coming_soon": "Editor de adhkār — en la próxima versión",
    "adhkar.editor.title": "Colecciones de Adhkār",
    "adhkar.editor.collections": "Colecciones",
    "adhkar.editor.new_collection": "Nueva colección",
    "adhkar.editor.untitled": "Sin título",
    "adhkar.editor.items_in": "Elementos en « %@ »",
    "adhkar.editor.add_from_library": "Añadir de la biblioteca…",
    "adhkar.editor.add_custom": "Añadir personalizado…",
    "adhkar.editor.no_collection_selected": "Selecciona una colección o crea una nueva.",
    "adhkar.editor.empty_collection": "Esta colección está vacía. Añade adhkār de la biblioteca o crea los tuyos.",
    "adhkar.editor.delete_collection": "¿Eliminar esta colección?",
    "adhkar.editor.delete_collection_msg": "Esta acción no se puede deshacer.",
    "adhkar.editor.delete_item": "¿Quitar este dhikr?",
    "adhkar.editor.repeat": "Repetición",
    "adhkar.editor.virtue": "Virtud / Notas",
    "adhkar.editor.source": "Fuente",
    "adhkar.editor.arabic": "Texto árabe",
    "adhkar.editor.audio": "Audio",
    "adhkar.editor.audio.choose": "Elegir audio…",
    "adhkar.editor.audio.import": "Importar archivo…",
    "adhkar.editor.audio.none": "Ninguno",
    "adhkar.editor.schedule": "Programación",
    "adhkar.editor.schedule.manual": "Manual (sin auto-play)",
    "adhkar.editor.schedule.shuruq": "Al amanecer (Shurūq)",
    "adhkar.editor.schedule.fajr": "Después de Fajr",
    "adhkar.editor.schedule.dhuhr": "Después de Dhuhr",
    "adhkar.editor.schedule.asr": "Después de Asr",
    "adhkar.editor.schedule.maghrib": "Después de Maghrib",
    "adhkar.editor.schedule.isha": "Después de Ishā",
    "adhkar.editor.autoplay": "Auto-reproducir a la hora programada",
    "adhkar.editor.save": "Guardar",
    "adhkar.editor.cancel": "Cancelar",
    "adhkar.editor.library_title": "Añadir de la biblioteca",
    "adhkar.editor.library_pick": "Elige los adhkār a añadir:",
    "adhkar.editor.library_add_selected": "Añadir selección",
    "adhkar.editor.custom_title": "Añadir dhikr personalizado",
    "adhkar.editor.custom_hint": "Escribe o pega el texto árabe, luego elige el número de repeticiones y el audio.",
    "adhkar.editor.move_up": "Subir",
    "adhkar.editor.move_down": "Bajar",
    "adhkar.editor.remove": "Quitar",
    "adhkar.editor.play_preview": "Previsualizar audio",
    "adhkar.import_audio": "Importar",
    "adhkar.editor.renamed": "Renombrado",
    "adhkar.editor.count_times": "%d veces"
  },
  "ar": {
    "col.prayer": "الصلاة",
    "col.adhan": "الأذان",
    "col.iqama": "الإقامة",
    "prayer.fajr": "الفجر",
    "prayer.shuruq": "الشروق",
    "prayer.dhuhr": "الظهر",
    "prayer.asr": "العصر",
    "prayer.maghrib": "المغرب",
    "prayer.isha": "العشاء",
    "label.jumua": "الجمعة",
    "label.next_prayer": "الصلاة التالية",
    "tooltip.refresh": "تحديث",
    "tooltip.language": "تغيير اللغة",
    "tooltip.theme": "السمة",
    "menu.theme.header.appearance": "المظهر",
    "menu.theme.appearance.system": "النظام",
    "menu.theme.appearance.light": "فاتح",
    "menu.theme.appearance.dark": "داكن",
    "menu.theme.header.accent": "لون التمييز",
    "menu.theme.accent.green": "أخضر",
    "menu.theme.accent.blue": "أزرق",
    "menu.theme.accent.purple": "بنفسجي",
    "menu.theme.accent.orange": "برتقالي",
    "menu.theme.accent.red": "أحمر",
    "menu.theme.accent.teal": "أزرق مخضر",
    "menu.theme.header.material": "الخلفية",
    "menu.theme.material.opaque": "معتم",
    "menu.theme.material.glass": "زجاج سائل",
    "tooltip.change": "تغيير المسجد",
    "tooltip.settings": "الإعدادات",
    "tooltip.back": "رجوع",
    "tooltip.test_adhan": "تجربة الأذان",
    "tooltip.stop_adhan": "إيقاف الأذان",
    "menubar.stop_adhan": "إيقاف الأذان",
    "mosque.default": "المسجد",
    "menu.open": "فتح أوقات الصلاة",
    "menu.refresh": "تحديث",
    "menu.choose": "اختيار المسجد…",
    "menu.settings": "الإعدادات…",
    "menu.favorites": "المفضلة",
    "menu.quit": "إنهاء",
    "settings.title": "الإعدادات",
    "settings.section.language": "اللغة",
    "settings.section.appearance": "المظهر",
    "settings.section.accent": "لون التمييز",
    "settings.section.material": "المادة",
    "settings.section.adhan": "الأذان",
    "settings.section.notifications": "الإشعارات",
    "settings.section.mosque": "المسجد",
    "settings.appearance.system": "النظام",
    "settings.appearance.light": "فاتح",
    "settings.appearance.dark": "داكن",
    "settings.adhan.play": "تشغيل صوت الأذان",
    "settings.adhan.sound": "الصوت",
    "settings.adhan.output": "الإخراج",
    "settings.adhan.output.default": "الافتراضي",
    "settings.notif.show": "إظهار الإشعارات",
    "settings.notif.headsup": "تنبيه قبل الصلاة",
    "settings.notif.headsup.off": "إيقاف",
    "settings.notif.headsup.minutes": "قبل %d دقيقة",
    "settings.notif.headsup.title": "%@ خلال %d دقيقة",
    "settings.mosque.currently": "حالياً",
    "settings.mosque.none": "لم يتم الاختيار",
    "settings.mosque.change": "تغيير المسجد",
    "settings.section.time_format": "تنسيق الوقت",
    "settings.time_format.24h": "٢٤ ساعة",
    "settings.time_format.12h": "١٢ ساعة",
    "settings.section.menu_bar": "شريط القائمة",
    "settings.bar.icon": "الأيقونة",
    "settings.bar.time": "وقت الصلاة",
    "settings.bar.countdown": "العد التنازلي",
    "settings.bar.hijri": "التاريخ الهجري",
    "settings.bar.hijri.format.off": "بدون",
    "settings.bar.hijri.format.full": "كامل (15 شوال 1447)",
    "settings.bar.hijri.format.daymonth": "اليوم + الشهر (15 شوال)",
    "settings.bar.hijri.format.month": "الشهر فقط (شوال)",
    "settings.bar.hijri.format.day": "اليوم فقط (15)",
    "settings.save": "حفظ",
    "settings.quit": "إنهاء",
    "header.openMosque": "فتح صفحة المسجد على mawaqit.net",
    "picker.title": "اختيار المسجد",
    "picker.btn.search": "بحث",
    "picker.btn.add": "إضافة",
    "picker.btn.near": "قريب",
    "picker.tab.favorites": "المفضلة",
    "picker.tab.search": "بحث",
    "picker.tab.near": "قريب",
    "picker.tab.url": "إضافة برابط",
    "picker.placeholder.search": "ابحث عن مدينة أو مسجد",
    "picker.placeholder.city": "مدينتك",
    "settings.tab.mosque": "المسجد",
    "settings.tab.appearance": "المظهر",
    "settings.tab.menu_bar": "شريط القائمة",
    "settings.tab.sound": "الصوت",
    "settings.section.startup": "بدء التشغيل",
    "settings.startup.open_at_login": "فتح عند تسجيل الدخول",
    "tooltip.open_at_login_failed": "رفض النظام تسجيل التطبيق. حاول مرة أخرى أو قم بالتفعيل من الإعدادات → عام → عناصر بدء التشغيل.",
    "picker.tooltip.remove_fav": "إزالة من المفضلة",
    "picker.tooltip.saved": "محفوظ في المفضلة",
    "picker.tooltip.add_fav": "إضافة إلى المفضلة",
    "picker.tooltip.is_default": "المسجد الحالي",
    "picker.tooltip.set_default": "تعيين كافتراضي",
    "picker.status.set_default_prefix": "تم التعيين كافتراضي:",
    "picker.status.added_fav_prefix": "تمت الإضافة للمفضلة:",
    "picker.status.removed_fav_prefix": "تمت الإزالة من المفضلة:",
    "menu.adhkar": "الأذكار",
    "adhkar.morning_title": "أذكار الصباح",
    "adhkar.evening_title": "أذكار المساء",
    "adhkar.play": "تشغيل",
    "adhkar.pause": "إيقاف مؤقت",
    "adhkar.mute": "كتم الصوت",
    "adhkar.unmute": "إلغاء الكتم",
    "adhkar.stop": "إيقاف",
    "adhkar.next": "الذكر التالي",
    "adhkar.prev": "الذكر السابق",
    "settings.section.adhkar": "الأذكار",
    "settings.adhkar.auto": "تلاوة أذكار الصباح والمساء تلقائيًا",
    "main.tab.prayer_times": "مواقيت الصلاة",
    "main.tab.adhkar": "الأذكار",
    "main.tab.adhan": "الأذان",
    "main.tab.settings": "الإعدادات",
    "menu.main_window": "فتح النافذة الرئيسية…",
    "adhkar.editor.coming_soon": "محرر الأذكار — في الإصدار القادم",
    "adhkar.editor.title": "مجموعات الأذكار",
    "adhkar.editor.collections": "المجموعات",
    "adhkar.editor.new_collection": "مجموعة جديدة",
    "adhkar.editor.untitled": "بدون عنوان",
    "adhkar.editor.items_in": "العناصر في «%@»",
    "adhkar.editor.add_from_library": "إضافة من المكتبة…",
    "adhkar.editor.add_custom": "إضافة مخصّص…",
    "adhkar.editor.no_collection_selected": "اختر مجموعة أو أنشئ واحدة جديدة.",
    "adhkar.editor.empty_collection": "هذه المجموعة فارغة. أضف أذكارًا من المكتبة أو أنشئ خاصتك.",
    "adhkar.editor.delete_collection": "حذف هذه المجموعة؟",
    "adhkar.editor.delete_collection_msg": "لا يمكن التراجع عن هذا الإجراء.",
    "adhkar.editor.delete_item": "إزالة هذا الذكر؟",
    "adhkar.editor.repeat": "التكرار",
    "adhkar.editor.virtue": "الفضل / ملاحظات",
    "adhkar.editor.source": "المصدر",
    "adhkar.editor.arabic": "النص العربي",
    "adhkar.editor.audio": "الصوت",
    "adhkar.editor.audio.choose": "اختر الصوت…",
    "adhkar.editor.audio.import": "استيراد ملف…",
    "adhkar.editor.audio.none": "بدون",
    "adhkar.editor.schedule": "الجدولة",
    "adhkar.editor.schedule.manual": "يدوي (بدن تشغيل تلقائي)",
    "adhkar.editor.schedule.shuruq": "عند الشروق",
    "adhkar.editor.schedule.fajr": "بعد الفجر",
    "adhkar.editor.schedule.dhuhr": "بعد الظهر",
    "adhkar.editor.schedule.asr": "بعد العصر",
    "adhkar.editor.schedule.maghrib": "بعد المغرب",
    "adhkar.editor.schedule.isha": "بعد العشاء",
    "adhkar.editor.autoplay": "تشغيل تلقائي في الوقت المحدد",
    "adhkar.editor.save": "حفظ",
    "adhkar.editor.cancel": "إلغاء",
    "adhkar.editor.library_title": "إضافة من المكتبة",
    "adhkar.editor.library_pick": "اختر الأذكار لإضافتها:",
    "adhkar.editor.library_add_selected": "إضافة المحدد",
    "adhkar.editor.custom_title": "إضافة ذكر مخصّص",
    "adhkar.editor.custom_hint": "اكتب أو الصق النص العربي، ثم اختر عدد التكرار والصوت.",
    "adhkar.editor.move_up": "تحريك لأعلى",
    "adhkar.editor.move_down": "تحريك لأسفل",
    "adhkar.editor.remove": "إزالة",
    "adhkar.editor.play_preview": "معاينة الصوت",
    "adhkar.import_audio": "استيراد",
    "adhkar.editor.renamed": "أُعيدت التسمية",
    "adhkar.editor.count_times": "%d مرات"
  },
  "zh": {
    "col.prayer": "礼拜",
    "col.adhan": "宣礼",
    "col.iqama": "伊卡麦",
    "prayer.fajr": "晨礼",
    "prayer.shuruq": "日出",
    "prayer.dhuhr": "晌礼",
    "prayer.asr": "晡礼",
    "prayer.maghrib": "昏礼",
    "prayer.isha": "宵礼",
    "label.jumua": "主麻",
    "label.next_prayer": "下次礼拜",
    "tooltip.refresh": "刷新",
    "tooltip.language": "更改语言",
    "tooltip.theme": "主题",
    "menu.theme.header.appearance": "外观",
    "menu.theme.appearance.system": "系统",
    "menu.theme.appearance.light": "浅色",
    "menu.theme.appearance.dark": "深色",
    "menu.theme.header.accent": "强调色",
    "menu.theme.accent.green": "绿色",
    "menu.theme.accent.blue": "蓝色",
    "menu.theme.accent.purple": "紫色",
    "menu.theme.accent.orange": "橙色",
    "menu.theme.accent.red": "红色",
    "menu.theme.accent.teal": "青色",
    "menu.theme.header.material": "背景",
    "menu.theme.material.opaque": "不透明",
    "menu.theme.material.glass": "液态玻璃",
    "tooltip.change": "更换清真寺",
    "tooltip.settings": "设置",
    "tooltip.back": "返回",
    "tooltip.test_adhan": "测试宣礼",
    "tooltip.stop_adhan": "停止宣礼",
    "mosque.default": "清真寺",
    "menu.open": "打开礼拜时间",
    "menu.refresh": "刷新",
    "menu.choose": "选择清真寺…",
    "menu.settings": "设置…",
    "menu.favorites": "收藏",
    "menu.quit": "退出",
    "settings.title": "设置",
    "settings.section.language": "语言",
    "settings.section.appearance": "外观",
    "settings.section.accent": "强调色",
    "settings.section.material": "材质",
    "settings.section.adhan": "宣礼",
    "settings.section.notifications": "通知",
    "settings.section.mosque": "清真寺",
    "settings.appearance.system": "系统",
    "settings.appearance.light": "浅色",
    "settings.appearance.dark": "深色",
    "settings.adhan.play": "播放宣礼声",
    "settings.adhan.sound": "声音",
    "settings.adhan.output": "输出",
    "settings.adhan.output.default": "系统默认",
    "settings.notif.show": "显示通知",
    "settings.mosque.currently": "当前",
    "settings.mosque.none": "未选择",
    "settings.mosque.change": "更换清真寺",
    "settings.section.time_format": "时间格式",
    "settings.time_format.24h": "24小时",
    "settings.time_format.12h": "12小时",
    "settings.section.menu_bar": "菜单栏",
    "settings.bar.icon": "图标",
    "settings.bar.time": "祈祷时间",
    "settings.bar.countdown": "倒计时",
    "settings.bar.hijri": "希吉来日期",
    "settings.bar.hijri.format.off": "关闭",
    "settings.bar.hijri.format.full": "完整 (15 Shawwāl 1447)",
    "settings.bar.hijri.format.daymonth": "日 + 月 (15 Shawwāl)",
    "settings.bar.hijri.format.month": "仅月份 (Shawwāl)",
    "settings.bar.hijri.format.day": "仅日期 (15)",
    "settings.quit": "退出",
    "picker.title": "选择清真寺",
    "picker.btn.search": "搜索",
    "picker.btn.add": "添加",
    "picker.btn.near": "附近",
    "picker.tab.favorites": "收藏",
    "picker.tab.search": "搜索",
    "picker.tab.near": "附近",
    "picker.tab.url": "通过URL添加",
    "picker.placeholder.search": "搜索城市或清真寺",
    "picker.placeholder.city": "你的城市",
    "settings.tab.mosque": "清真寺",
    "settings.tab.appearance": "外观",
    "settings.tab.menu_bar": "菜单栏",
    "settings.tab.sound": "声音",
    "settings.section.startup": "启动",
    "settings.startup.open_at_login": "登录时打开",
    "tooltip.open_at_login_failed": "macOS 拒绝注册登录项。请重试,或在 系统设置 → 通用 → 登录项 中启用。",
    "picker.tooltip.remove_fav": "从收藏中移除",
    "picker.tooltip.saved": "已收藏",
    "picker.tooltip.add_fav": "添加到收藏",
    "picker.tooltip.is_default": "当前默认",
    "picker.tooltip.set_default": "设为默认",
    "picker.status.set_default_prefix": "设为默认:",
    "picker.status.added_fav_prefix": "已添加到收藏:",
    "picker.status.removed_fav_prefix": "已从收藏中移除:",
    "menu.adhkar": "赞词",
    "adhkar.morning_title": "晨间赞词",
    "adhkar.evening_title": "晚间赞词",
    "adhkar.play": "播放",
    "adhkar.pause": "暂停",
    "adhkar.mute": "静音",
    "adhkar.unmute": "取消静音",
    "adhkar.stop": "停止",
    "adhkar.next": "下一条",
    "adhkar.prev": "上一条",
    "settings.section.adhkar": "赞词",
    "settings.adhkar.auto": "自动诵读晨间与晚间赞词",
    "main.tab.prayer_times": "礼拜时间",
    "main.tab.adhkar": "赞词",
    "main.tab.adhan": "宣礼",
    "main.tab.settings": "设置",
    "menu.main_window": "打开主窗口…",
    "adhkar.editor.coming_soon": "赞词编辑器 — 将在下个版本推出",
    "adhkar.editor.title": "赞词合集",
    "adhkar.editor.collections": "合集",
    "adhkar.editor.new_collection": "新建合集",
    "adhkar.editor.untitled": "未命名",
    "adhkar.editor.items_in": "“%@” 中的项目",
    "adhkar.editor.add_from_library": "从库中添加…",
    "adhkar.editor.add_custom": "添加自定义…",
    "adhkar.editor.no_collection_selected": "选择一个合集或新建一个。",
    "adhkar.editor.empty_collection": "此合集中没有项目。从库中添加或创建自己的赞词。",
    "adhkar.editor.delete_collection": "删除此合集？",
    "adhkar.editor.delete_collection_msg": "此操作无法撤销。",
    "adhkar.editor.delete_item": "移除此赞词？",
    "adhkar.editor.repeat": "重复次数",
    "adhkar.editor.virtue": "益处 / 备注",
    "adhkar.editor.source": "来源",
    "adhkar.editor.arabic": "阿拉伯文",
    "adhkar.editor.audio": "音频",
    "adhkar.editor.audio.choose": "选择音频…",
    "adhkar.editor.audio.import": "导入文件…",
    "adhkar.editor.audio.none": "无",
    "adhkar.editor.schedule": "计划",
    "adhkar.editor.schedule.manual": "手动（不自动播放）",
    "adhkar.editor.schedule.shuruq": "日出时",
    "adhkar.editor.schedule.fajr": "晨礼后",
    "adhkar.editor.schedule.dhuhr": "晌礼后",
    "adhkar.editor.schedule.asr": "晡礼后",
    "adhkar.editor.schedule.maghrib": "昏礼后",
    "adhkar.editor.schedule.isha": "宵礼后",
    "adhkar.editor.autoplay": "在计划时间自动播放",
    "adhkar.editor.save": "保存",
    "adhkar.editor.cancel": "取消",
    "adhkar.editor.library_title": "从库中添加",
    "adhkar.editor.library_pick": "选择要添加的赞词：",
    "adhkar.editor.library_add_selected": "添加所选",
    "adhkar.editor.custom_title": "添加自定义赞词",
    "adhkar.editor.custom_hint": "输入或粘贴阿拉伯文，然后选择重复次数和音频。",
    "adhkar.editor.move_up": "上移",
    "adhkar.editor.move_down": "下移",
    "adhkar.editor.remove": "移除",
    "adhkar.editor.play_preview": "预览音频",
    "adhkar.import_audio": "导入",
    "adhkar.editor.renamed": "已重命名",
    "adhkar.editor.count_times": "%d 次"
  },
  "hi": {
    "col.prayer": "नमाज़",
    "col.adhan": "अज़ान",
    "col.iqama": "इक़ामा",
    "prayer.fajr": "फ़ज्र",
    "prayer.shuruq": "सूर्योदय",
    "prayer.dhuhr": "ज़ुहर",
    "prayer.asr": "अस्र",
    "prayer.maghrib": "मग़रिब",
    "prayer.isha": "इशा",
    "label.jumua": "जुमा",
    "label.next_prayer": "अगली नमाज़",
    "tooltip.refresh": "ताज़ा करें",
    "tooltip.language": "भाषा बदलें",
    "tooltip.theme": "थीम",
    "menu.theme.header.appearance": "स्वरूप",
    "menu.theme.appearance.system": "सिस्टम",
    "menu.theme.appearance.light": "उजला",
    "menu.theme.appearance.dark": "गहरा",
    "menu.theme.header.accent": "एक्सेंट रंग",
    "menu.theme.accent.green": "हरा",
    "menu.theme.accent.blue": "नीला",
    "menu.theme.accent.purple": "बैंगनी",
    "menu.theme.accent.orange": "नारंगी",
    "menu.theme.accent.red": "लाल",
    "menu.theme.accent.teal": "टील",
    "menu.theme.header.material": "पृष्ठभूमि",
    "menu.theme.material.opaque": "अपारदर्शी",
    "menu.theme.material.glass": "लिक्विड ग्लास",
    "tooltip.change": "मस्जिद बदलें",
    "tooltip.settings": "सेटिंग्स",
    "tooltip.back": "वापस",
    "tooltip.test_adhan": "अज़ान परीक्षण",
    "tooltip.stop_adhan": "अज़ान रोकें",
    "mosque.default": "मस्जिद",
    "menu.open": "सलात टाइम खोलें",
    "menu.refresh": "ताज़ा करें",
    "menu.choose": "मस्जिद चुनें…",
    "menu.settings": "सेटिंग्स…",
    "menu.favorites": "पसंदीदा",
    "menu.quit": "बंद करें",
    "settings.title": "सेटिंग्स",
    "settings.section.language": "भाषा",
    "settings.section.appearance": "रूप",
    "settings.section.accent": "एक्सेंट रंग",
    "settings.section.material": "मटीरियल",
    "settings.section.adhan": "अज़ान",
    "settings.section.notifications": "सूचनाएँ",
    "settings.section.mosque": "मस्जिद",
    "settings.appearance.system": "सिस्टम",
    "settings.appearance.light": "हल्का",
    "settings.appearance.dark": "गहरा",
    "settings.adhan.play": "अज़ान ध्वनि चलाएँ",
    "settings.adhan.sound": "ध्वनि",
    "settings.adhan.output": "आउटपुट",
    "settings.adhan.output.default": "सिस्टम डिफ़ॉल्ट",
    "settings.notif.show": "सूचनाएँ दिखाएँ",
    "settings.mosque.currently": "वर्तमान में",
    "settings.mosque.none": "कोई नहीं चुना",
    "settings.mosque.change": "मस्जिद बदलें",
    "settings.section.time_format": "समय प्रारूप",
    "settings.time_format.24h": "24-घंटे",
    "settings.time_format.12h": "12-घंटे",
    "settings.section.menu_bar": "मेनू बार",
    "settings.bar.icon": "आइकन",
    "settings.bar.time": "निर्धारित समय",
    "settings.bar.countdown": "उलटी गिनती",
    "settings.bar.hijri": "हिजरी तिथि",
    "settings.bar.hijri.format.off": "बंद",
    "settings.bar.hijri.format.full": "पूर्ण (15 Shawwāl 1447)",
    "settings.bar.hijri.format.daymonth": "दिन + महीना (15 Shawwāl)",
    "settings.bar.hijri.format.month": "केवल महीना (Shawwāl)",
    "settings.bar.hijri.format.day": "केवल दिन (15)",
    "settings.quit": "बंद करें",
    "picker.title": "मस्जिद चुनें",
    "picker.btn.search": "खोजें",
    "picker.btn.add": "जोड़ें",
    "picker.btn.near": "निकट",
    "picker.tab.favorites": "पसंदीदा",
    "picker.tab.search": "खोजें",
    "picker.tab.near": "निकट",
    "picker.tab.url": "URL से जोड़ें",
    "picker.placeholder.search": "शहर या मस्जिद खोजें",
    "picker.placeholder.city": "आपका शहर",
    "settings.tab.mosque": "मस्जिद",
    "settings.tab.appearance": "स्वरूप",
    "settings.tab.menu_bar": "मेनू बार",
    "settings.tab.sound": "ध्वनि",
    "settings.section.startup": "प्रारंभ",
    "settings.startup.open_at_login": "लॉगिन पर खोलें",
    "tooltip.open_at_login_failed": "macOS ने पंजीकरण अस्वीकार कर दिया। सिस्टम सेटिंग्स → सामान्य → लॉगिन आइटम से सक्षम करें।",
    "picker.tooltip.remove_fav": "पसंदीदा से हटाएँ",
    "picker.tooltip.saved": "पसंदीदा में सहेजा गया",
    "picker.tooltip.add_fav": "पसंदीदा में जोड़ें",
    "picker.tooltip.is_default": "वर्तमान डिफ़ॉल्ट",
    "picker.tooltip.set_default": "डिफ़ॉल्ट बनाएँ",
    "picker.status.set_default_prefix": "डिफ़ॉल्ट बनाया:",
    "picker.status.added_fav_prefix": "पसंदीदा में जोड़ा:",
    "picker.status.removed_fav_prefix": "पसंदीदा से हटाया:",
    "menu.adhkar": "अज़्कार",
    "adhkar.morning_title": "सुबह के अज़्कार",
    "adhkar.evening_title": "शाम के अज़्कार",
    "adhkar.play": "चलाएँ",
    "adhkar.pause": "रोकें",
    "adhkar.mute": "मौन करें",
    "adhkar.unmute": "मौन हटाएँ",
    "adhkar.stop": "बंद करें",
    "adhkar.next": "अगला ज़िक्र",
    "adhkar.prev": "पिछला ज़िक्र",
    "settings.section.adhkar": "अज़्कार",
    "settings.adhkar.auto": "सुबह और शाम के अज़्कार स्वतः पढ़ें",
    "main.tab.prayer_times": "नमाज़ के समय",
    "main.tab.adhkar": "अज़्कार",
    "main.tab.adhan": "अज़ान",
    "main.tab.settings": "सेटिंग्स",
    "menu.main_window": "मुख्य विंडो खोलें…",
    "adhkar.editor.coming_soon": "अज़्कार संपादक — अगले संस्करण में",
    "adhkar.editor.title": "अज़्कार संग्रह",
    "adhkar.editor.collections": "संग्रह",
    "adhkar.editor.new_collection": "नया संग्रह",
    "adhkar.editor.untitled": "बिना शीर्षक",
    "adhkar.editor.items_in": "“%@” में आइटम",
    "adhkar.editor.add_from_library": "लाइब्रेरी से जोड़ें…",
    "adhkar.editor.add_custom": "कस्टम जोड़ें…",
    "adhkar.editor.no_collection_selected": "एक संग्रह चुनें या नया बनाएँ।",
    "adhkar.editor.empty_collection": "यह संग्रह खाली है। लाइब्रेरी से अज़्कार जोड़ें या अपना बनाएँ।",
    "adhkar.editor.delete_collection": "इस संग्रह को हटाएँ?",
    "adhkar.editor.delete_collection_msg": "यह पूर्ववत नहीं किया जा सकता।",
    "adhkar.editor.delete_item": "इस ज़िक्र को हटाएँ?",
    "adhkar.editor.repeat": "दोहराव",
    "adhkar.editor.virtue": "गुण / नोट्स",
    "adhkar.editor.source": "स्रोत",
    "adhkar.editor.arabic": "अरबी पाठ",
    "adhkar.editor.audio": "ऑडियो",
    "adhkar.editor.audio.choose": "ऑडियो चुनें…",
    "adhkar.editor.audio.import": "फ़ाइल आयात करें…",
    "adhkar.editor.audio.none": "कोई नहीं",
    "adhkar.editor.schedule": "अनुसूची",
    "adhkar.editor.schedule.manual": "मैन्युअल (कोई ऑटो-प्ले नहीं)",
    "adhkar.editor.schedule.shuruq": "सूर्योदय पर",
    "adhkar.editor.schedule.fajr": "फज्र के बाद",
    "adhkar.editor.schedule.dhuhr": "ज़ुहर के बाद",
    "adhkar.editor.schedule.asr": "अस्र के बाद",
    "adhkar.editor.schedule.maghrib": "मग़रिब के बाद",
    "adhkar.editor.schedule.isha": "इशा के बाद",
    "adhkar.editor.autoplay": "निर्धारित समय पर स्वतः चलाएँ",
    "adhkar.editor.save": "सहेजें",
    "adhkar.editor.cancel": "रद्द करें",
    "adhkar.editor.library_title": "लाइब्रेरी से जोड़ें",
    "adhkar.editor.library_pick": "जोड़ने के लिए अज़्कार चुनें:",
    "adhkar.editor.library_add_selected": "चयनित जोड़ें",
    "adhkar.editor.custom_title": "कस्टम ज़िक्र जोड़ें",
    "adhkar.editor.custom_hint": "अरबी पाठ टाइप या पेस्ट करें, फिर दोहराव और ऑडियो चुनें।",
    "adhkar.editor.move_up": "ऊपर ले जाएँ",
    "adhkar.editor.move_down": "नीचे ले जाएँ",
    "adhkar.editor.remove": "हटाएँ",
    "adhkar.editor.play_preview": "ऑडियो पूर्वावलोकन",
    "adhkar.import_audio": "आयात",
    "adhkar.editor.renamed": "नाम बदला गया",
    "adhkar.editor.count_times": "%d बार"
  },
  "bn": {
    "col.prayer": "নামাজ",
    "col.adhan": "আযান",
    "col.iqama": "ইকামা",
    "prayer.fajr": "ফজর",
    "prayer.shuruq": "সূর্যোদয়",
    "prayer.dhuhr": "যোহর",
    "prayer.asr": "আসর",
    "prayer.maghrib": "মাগরিব",
    "prayer.isha": "এশা",
    "label.jumua": "জুমু'আ",
    "label.next_prayer": "পরবর্তী নামাজ",
    "tooltip.refresh": "রিফ্রেশ",
    "tooltip.language": "ভাষা পরিবর্তন করুন",
    "tooltip.theme": "থিম",
    "menu.theme.header.appearance": "চেহারা",
    "menu.theme.appearance.system": "সিস্টেম",
    "menu.theme.appearance.light": "হালকা",
    "menu.theme.appearance.dark": "গাঢ়",
    "menu.theme.header.accent": "অ্যাকসেন্ট রঙ",
    "menu.theme.accent.green": "সবুজ",
    "menu.theme.accent.blue": "নীল",
    "menu.theme.accent.purple": "বেগুনি",
    "menu.theme.accent.orange": "কমলা",
    "menu.theme.accent.red": "লাল",
    "menu.theme.accent.teal": "টিল",
    "menu.theme.header.material": "পটভূমি",
    "menu.theme.material.opaque": "অস্বচ্ছ",
    "menu.theme.material.glass": "লিকুইড গ্লাস",
    "tooltip.change": "মসজিদ পরিবর্তন",
    "tooltip.settings": "সেটিংস",
    "tooltip.back": "ফিরে যান",
    "tooltip.test_adhan": "আযান পরীক্ষা",
    "tooltip.stop_adhan": "আযান বন্ধ করুন",
    "mosque.default": "মসজিদ",
    "menu.open": "সালাত টাইম খুলুন",
    "menu.refresh": "রিফ্রেশ",
    "menu.choose": "মসজিদ নির্বাচন…",
    "menu.settings": "সেটিংস…",
    "menu.favorites": "প্রিয়",
    "menu.quit": "বন্ধ",
    "settings.title": "সেটিংস",
    "settings.section.language": "ভাষা",
    "settings.section.appearance": "চেহারা",
    "settings.section.accent": "অ্যাকসেন্ট রঙ",
    "settings.section.material": "ম্যাটেরিয়াল",
    "settings.section.adhan": "আযান",
    "settings.section.notifications": "বিজ্ঞপ্তি",
    "settings.section.mosque": "মসজিদ",
    "settings.appearance.system": "সিস্টেম",
    "settings.appearance.light": "হালকা",
    "settings.appearance.dark": "গাঢ়",
    "settings.adhan.play": "আযান বাজান",
    "settings.adhan.sound": "শব্দ",
    "settings.adhan.output": "আউটপুট",
    "settings.adhan.output.default": "সিস্টেম ডিফল্ট",
    "settings.notif.show": "বিজ্ঞপ্তি দেখান",
    "settings.mosque.currently": "বর্তমানে",
    "settings.mosque.none": "কিছু নির্বাচিত নয়",
    "settings.mosque.change": "মসজিদ পরিবর্তন",
    "settings.section.time_format": "সময় বিন্যাস",
    "settings.time_format.24h": "২৪-ঘণ্টা",
    "settings.time_format.12h": "১২-ঘণ্টা",
    "settings.section.menu_bar": "মেনু বার",
    "settings.bar.icon": "আইকন",
    "settings.bar.time": "নির্ধারিত সময়",
    "settings.bar.countdown": "কাউন্টডাউন",
    "settings.bar.hijri": "হিজরি তারিখ",
    "settings.bar.hijri.format.off": "বন্ধ",
    "settings.bar.hijri.format.full": "সম্পূর্ণ (15 Shawwāl 1447)",
    "settings.bar.hijri.format.daymonth": "দিন + মাস (15 Shawwāl)",
    "settings.bar.hijri.format.month": "শুধু মাস (Shawwāl)",
    "settings.bar.hijri.format.day": "শুধু দিন (15)",
    "settings.quit": "বন্ধ",
    "picker.title": "মসজিদ নির্বাচন",
    "picker.btn.search": "খুঁজুন",
    "picker.btn.add": "যোগ করুন",
    "picker.btn.near": "কাছাকাছি",
    "picker.tab.favorites": "প্রিয়",
    "picker.tab.search": "খুঁজুন",
    "picker.tab.near": "কাছাকাছি",
    "picker.tab.url": "URL দিয়ে যোগ করুন",
    "picker.placeholder.search": "শহর বা মসজিদ খুঁজুন",
    "picker.placeholder.city": "আপনার শহর",
    "settings.tab.mosque": "মসজিদ",
    "settings.tab.appearance": "চেহারা",
    "settings.tab.menu_bar": "মেনু বার",
    "settings.tab.sound": "শব্দ",
    "settings.section.startup": "শুরু",
    "settings.startup.open_at_login": "লগইনে খুলুন",
    "tooltip.open_at_login_failed": "macOS নিবন্ধন অস্বীকার করেছে। সিস্টেম সেটিংস → সাধারণ → লগইন আইটেম থেকে সক্ষম করুন।",
    "picker.tooltip.remove_fav": "পছন্দ থেকে সরান",
    "picker.tooltip.saved": "পছন্দে সংরক্ষিত",
    "picker.tooltip.add_fav": "পছন্দে যুক্ত করুন",
    "picker.tooltip.is_default": "বর্তমান ডিফল্ট",
    "picker.tooltip.set_default": "ডিফল্ট করুন",
    "picker.status.set_default_prefix": "ডিফল্ট করা হয়েছে:",
    "picker.status.added_fav_prefix": "পছন্দে যুক্ত:",
    "picker.status.removed_fav_prefix": "পছন্দ থেকে সরানো হয়েছে:",
    "menu.adhkar": "আজকার",
    "adhkar.morning_title": "সকালের আজকার",
    "adhkar.evening_title": "সন্ধ্যার আজকার",
    "adhkar.play": "চালান",
    "adhkar.pause": "বিরতি",
    "adhkar.mute": "শব্দ বন্ধ",
    "adhkar.unmute": "শব্দ চালু",
    "adhkar.stop": "বন্ধ করুন",
    "adhkar.next": "পরবর্তী জিকর",
    "adhkar.prev": "পূর্ববর্তী জিকর",
    "settings.section.adhkar": "আজকার",
    "settings.adhkar.auto": "সকাল ও সন্ধ্যার আজকার স্বয়ংক্রিয়ভাবে পাঠ করুন",
    "main.tab.prayer_times": "নামাজের সময়",
    "main.tab.adhkar": "আজকার",
    "main.tab.adhan": "আজান",
    "main.tab.settings": "সেটিংস",
    "menu.main_window": "মূল উইন্ডো খুলুন…",
    "adhkar.editor.coming_soon": "আজকার সম্পাদক — পরবর্তী সংস্করণে",
    "adhkar.editor.title": "আজকার সংগ্রহ",
    "adhkar.editor.collections": "সংগ্রহ",
    "adhkar.editor.new_collection": "নতুন সংগ্রহ",
    "adhkar.editor.untitled": "শিরোনামহীন",
    "adhkar.editor.items_in": "“%@” এ আইটেম",
    "adhkar.editor.add_from_library": "লাইব্রেরি থেকে যোগ করুন…",
    "adhkar.editor.add_custom": "কাস্টম যোগ করুন…",
    "adhkar.editor.no_collection_selected": "একটি সংগ্রহ নির্বাচন করুন বা নতুন তৈরি করুন।",
    "adhkar.editor.empty_collection": "এই সংগ্রহটি খালি। লাইব্রেরি থেকে আজকার যোগ করুন বা নিজে তৈরি করুন।",
    "adhkar.editor.delete_collection": "এই সংগ্রহটি মুছবেন?",
    "adhkar.editor.delete_collection_msg": "এটি পূর্বাবস্থায় ফেরানো যাবে না।",
    "adhkar.editor.delete_item": "এই জিকর সরাবেন?",
    "adhkar.editor.repeat": "পুনরাবৃত্তি",
    "adhkar.editor.virtue": "গুণ / নোট",
    "adhkar.editor.source": "উৎস",
    "adhkar.editor.arabic": "আরবি টেক্সট",
    "adhkar.editor.audio": "অডিও",
    "adhkar.editor.audio.choose": "অডিও বাছাই করুন…",
    "adhkar.editor.audio.import": "ফাইল আমদানি…",
    "adhkar.editor.audio.none": "কোনোটি নয়",
    "adhkar.editor.schedule": "সূচি",
    "adhkar.editor.schedule.manual": "ম্যানুয়াল (কোনো অটো-প্লে নয়)",
    "adhkar.editor.schedule.shuruq": "সূর্যোদয়ে",
    "adhkar.editor.schedule.fajr": "ফজরের পরে",
    "adhkar.editor.schedule.dhuhr": "জোহরের পরে",
    "adhkar.editor.schedule.asr": "আসরের পরে",
    "adhkar.editor.schedule.maghrib": "মাগরিবের পরে",
    "adhkar.editor.schedule.isha": "এশার পরে",
    "adhkar.editor.autoplay": "নির্ধারিত সময়ে স্বয়ংক্রিয় প্লে",
    "adhkar.editor.save": "সংরক্ষণ",
    "adhkar.editor.cancel": "বাতিল",
    "adhkar.editor.library_title": "লাইব্রেরি থেকে যোগ করুন",
    "adhkar.editor.library_pick": "যোগ করতে আজকার বাছাই করুন:",
    "adhkar.editor.library_add_selected": "নির্বাচিত যোগ করুন",
    "adhkar.editor.custom_title": "কাস্টম জিকর যোগ করুন",
    "adhkar.editor.custom_hint": "আরবি টেক্সট টাইপ বা পেস্ট করুন, তারপর পুনরাবৃত্তি ও অডিও বাছাই করুন।",
    "adhkar.editor.move_up": "উপরে",
    "adhkar.editor.move_down": "নিচে",
    "adhkar.editor.remove": "সরান",
    "adhkar.editor.play_preview": "অডিও প্রিভিউ",
    "adhkar.import_audio": "আমদানি",
    "adhkar.editor.renamed": "নামকরণ হয়েছে",
    "adhkar.editor.count_times": "%d বার"
  },
  "ru": {
    "col.prayer": "Молитва",
    "col.adhan": "Азан",
    "col.iqama": "Икама",
    "prayer.fajr": "Фаджр",
    "prayer.shuruq": "Восход",
    "prayer.dhuhr": "Зухр",
    "prayer.asr": "Аср",
    "prayer.maghrib": "Магриб",
    "prayer.isha": "Иша",
    "label.jumua": "Джума",
    "label.next_prayer": "Следующая молитва",
    "tooltip.refresh": "Обновить",
    "tooltip.language": "Сменить язык",
    "tooltip.theme": "Тема",
    "menu.theme.header.appearance": "Оформление",
    "menu.theme.appearance.system": "Системное",
    "menu.theme.appearance.light": "Светлое",
    "menu.theme.appearance.dark": "Тёмное",
    "menu.theme.header.accent": "Акцентный цвет",
    "menu.theme.accent.green": "Зелёный",
    "menu.theme.accent.blue": "Синий",
    "menu.theme.accent.purple": "Фиолетовый",
    "menu.theme.accent.orange": "Оранжевый",
    "menu.theme.accent.red": "Красный",
    "menu.theme.accent.teal": "Бирюзовый",
    "menu.theme.header.material": "Фон",
    "menu.theme.material.opaque": "Непрозрачный",
    "menu.theme.material.glass": "Жидкое стекло",
    "tooltip.change": "Сменить мечеть",
    "tooltip.settings": "Настройки",
    "tooltip.back": "Назад",
    "tooltip.test_adhan": "Проверить азан",
    "tooltip.stop_adhan": "Остановить азан",
    "mosque.default": "Мечеть",
    "menu.open": "Открыть Salat Time",
    "menu.refresh": "Обновить",
    "menu.choose": "Выбрать мечеть…",
    "menu.settings": "Настройки…",
    "menu.favorites": "Избранное",
    "menu.quit": "Выход",
    "settings.title": "Настройки",
    "settings.section.language": "Язык",
    "settings.section.appearance": "Оформление",
    "settings.section.accent": "Акцентный цвет",
    "settings.section.material": "Материал",
    "settings.section.adhan": "Азан",
    "settings.section.notifications": "Уведомления",
    "settings.section.mosque": "Мечеть",
    "settings.appearance.system": "Системное",
    "settings.appearance.light": "Светлое",
    "settings.appearance.dark": "Тёмное",
    "settings.adhan.play": "Проигрывать азан",
    "settings.adhan.sound": "Звук",
    "settings.adhan.output": "Вывод",
    "settings.adhan.output.default": "По умолчанию",
    "settings.notif.show": "Показывать уведомления",
    "settings.mosque.currently": "Сейчас",
    "settings.mosque.none": "Не выбрана",
    "settings.mosque.change": "Сменить мечеть",
    "settings.section.time_format": "Формат времени",
    "settings.time_format.24h": "24 ч",
    "settings.time_format.12h": "12 ч",
    "settings.section.menu_bar": "Строка меню",
    "settings.bar.icon": "Значок",
    "settings.bar.time": "Время намаза",
    "settings.bar.countdown": "Обратный отсчёт",
    "settings.bar.hijri": "Дата Хиджры",
    "settings.bar.hijri.format.off": "Выкл.",
    "settings.bar.hijri.format.full": "Полная (15 Shawwāl 1447)",
    "settings.bar.hijri.format.daymonth": "День + месяц (15 Shawwāl)",
    "settings.bar.hijri.format.month": "Только месяц (Shawwāl)",
    "settings.bar.hijri.format.day": "Только день (15)",
    "settings.quit": "Выход",
    "picker.title": "Выбрать мечеть",
    "picker.btn.search": "Поиск",
    "picker.btn.add": "Добавить",
    "picker.btn.near": "Рядом",
    "picker.tab.favorites": "Избранное",
    "picker.tab.search": "Поиск",
    "picker.tab.near": "Рядом",
    "picker.tab.url": "Добавить по URL",
    "picker.placeholder.search": "Найти город или мечеть",
    "picker.placeholder.city": "Ваш город",
    "settings.tab.mosque": "Мечеть",
    "settings.tab.appearance": "Оформление",
    "settings.tab.menu_bar": "Строка меню",
    "settings.tab.sound": "Звук",
    "settings.section.startup": "Запуск",
    "settings.startup.open_at_login": "Открывать при входе",
    "tooltip.open_at_login_failed": "macOS отклонил регистрацию. Включите в Системных настройках → Основные → Объекты входа.",
    "picker.tooltip.remove_fav": "Убрать из избранного",
    "picker.tooltip.saved": "Сохранено в избранное",
    "picker.tooltip.add_fav": "Добавить в избранное",
    "picker.tooltip.is_default": "Текущая мечеть",
    "picker.tooltip.set_default": "Сделать основной",
    "picker.status.set_default_prefix": "Основная:",
    "picker.status.added_fav_prefix": "Добавлено в избранное:",
    "picker.status.removed_fav_prefix": "Удалено из избранного:",
    "menu.adhkar": "Азкар",
    "adhkar.morning_title": "Утренние азкар",
    "adhkar.evening_title": "Вечерние азкар",
    "adhkar.play": "Воспроизвести",
    "adhkar.pause": "Пауза",
    "adhkar.mute": "Без звука",
    "adhkar.unmute": "Включить звук",
    "adhkar.stop": "Остановить",
    "adhkar.next": "Следующий зикр",
    "adhkar.prev": "Предыдущий зикр",
    "settings.section.adhkar": "Азкар",
    "settings.adhkar.auto": "Автоматически читать утренние и вечерние азкар",
    "main.tab.prayer_times": "Времена молитв",
    "main.tab.adhkar": "Азкар",
    "main.tab.adhan": "Азан",
    "main.tab.settings": "Настройки",
    "menu.main_window": "Открыть главное окно…",
    "adhkar.editor.coming_soon": "Редактор азкар — в следующей сборке",
    "adhkar.editor.title": "Коллекции азкар",
    "adhkar.editor.collections": "Коллекции",
    "adhkar.editor.new_collection": "Новая коллекция",
    "adhkar.editor.untitled": "Без названия",
    "adhkar.editor.items_in": "Элементы в «%@»",
    "adhkar.editor.add_from_library": "Добавить из библиотеки…",
    "adhkar.editor.add_custom": "Добавить свой…",
    "adhkar.editor.no_collection_selected": "Выберите коллекцию или создайте новую.",
    "adhkar.editor.empty_collection": "Эта коллекция пуста. Добавьте азкар из библиотеки или создайте свои.",
    "adhkar.editor.delete_collection": "Удалить эту коллекцию?",
    "adhkar.editor.delete_collection_msg": "Это действие нельзя отменить.",
    "adhkar.editor.delete_item": "Удалить этот зикр?",
    "adhkar.editor.repeat": "Повтор",
    "adhkar.editor.virtue": "Достоинство / Заметки",
    "adhkar.editor.source": "Источник",
    "adhkar.editor.arabic": "Арабский текст",
    "adhkar.editor.audio": "Аудио",
    "adhkar.editor.audio.choose": "Выбрать аудио…",
    "adhkar.editor.audio.import": "Импорт файла…",
    "adhkar.editor.audio.none": "Нет",
    "adhkar.editor.schedule": "Расписание",
    "adhkar.editor.schedule.manual": "Вручную (без авто-воспроизведения)",
    "adhkar.editor.schedule.shuruq": "На рассвете (Шурук)",
    "adhkar.editor.schedule.fajr": "После Фаджра",
    "adhkar.editor.schedule.dhuhr": "После Зухра",
    "adhkar.editor.schedule.asr": "После Асра",
    "adhkar.editor.schedule.maghrib": "После Магриба",
    "adhkar.editor.schedule.isha": "После Иша",
    "adhkar.editor.autoplay": "Авто-воспроизведение по расписанию",
    "adhkar.editor.save": "Сохранить",
    "adhkar.editor.cancel": "Отмена",
    "adhkar.editor.library_title": "Добавить из библиотеки",
    "adhkar.editor.library_pick": "Выберите азкар для добавления:",
    "adhkar.editor.library_add_selected": "Добавить выбранные",
    "adhkar.editor.custom_title": "Добавить свой зикр",
    "adhkar.editor.custom_hint": "Введите или вставьте арабский текст, затем выберите количество повторов и аудио.",
    "adhkar.editor.move_up": "Вверх",
    "adhkar.editor.move_down": "Вниз",
    "adhkar.editor.remove": "Удалить",
    "adhkar.editor.play_preview": "Прослушать аудио",
    "adhkar.import_audio": "Импорт",
    "adhkar.editor.renamed": "Переименовано",
    "adhkar.editor.count_times": "%d раз"
  },
  "pt": {
    "col.prayer": "Oração",
    "col.adhan": "Adhan",
    "col.iqama": "Iqama",
    "prayer.fajr": "Fajr",
    "prayer.shuruq": "Nascer do sol",
    "prayer.dhuhr": "Dhuhr",
    "prayer.asr": "Asr",
    "prayer.maghrib": "Maghrib",
    "prayer.isha": "Isha",
    "label.jumua": "Jumu'ah",
    "label.next_prayer": "Próxima oração",
    "tooltip.refresh": "Atualizar",
    "tooltip.language": "Alterar idioma",
    "tooltip.theme": "Tema",
    "menu.theme.header.appearance": "Aparência",
    "menu.theme.appearance.system": "Sistema",
    "menu.theme.appearance.light": "Claro",
    "menu.theme.appearance.dark": "Escuro",
    "menu.theme.header.accent": "Cor de destaque",
    "menu.theme.accent.green": "Verde",
    "menu.theme.accent.blue": "Azul",
    "menu.theme.accent.purple": "Roxo",
    "menu.theme.accent.orange": "Laranja",
    "menu.theme.accent.red": "Vermelho",
    "menu.theme.accent.teal": "Verde-azulado",
    "menu.theme.header.material": "Plano de fundo",
    "menu.theme.material.opaque": "Opaco",
    "menu.theme.material.glass": "Vidro líquido",
    "tooltip.change": "Mudar mesquita",
    "tooltip.settings": "Configurações",
    "tooltip.back": "Voltar",
    "tooltip.test_adhan": "Testar adhan",
    "tooltip.stop_adhan": "Parar adhan",
    "mosque.default": "Mesquita",
    "menu.open": "Abrir Salat Time",
    "menu.refresh": "Atualizar",
    "menu.choose": "Escolher mesquita…",
    "menu.settings": "Configurações…",
    "menu.favorites": "Favoritos",
    "menu.quit": "Sair",
    "settings.title": "Configurações",
    "settings.section.language": "Idioma",
    "settings.section.appearance": "Aparência",
    "settings.section.accent": "Cor de destaque",
    "settings.section.material": "Material",
    "settings.section.adhan": "Adhan",
    "settings.section.notifications": "Notificações",
    "settings.section.mosque": "Mesquita",
    "settings.appearance.system": "Sistema",
    "settings.appearance.light": "Claro",
    "settings.appearance.dark": "Escuro",
    "settings.adhan.play": "Reproduzir adhan",
    "settings.adhan.sound": "Som",
    "settings.adhan.output": "Saída",
    "settings.adhan.output.default": "Padrão do sistema",
    "settings.notif.show": "Mostrar notificações",
    "settings.mosque.currently": "Atualmente",
    "settings.mosque.none": "Nenhuma selecionada",
    "settings.mosque.change": "Mudar mesquita",
    "settings.section.time_format": "Formato da hora",
    "settings.time_format.24h": "24 h",
    "settings.time_format.12h": "12 h",
    "settings.section.menu_bar": "Barra de menu",
    "settings.bar.icon": "Ícone",
    "settings.bar.time": "Hora programada",
    "settings.bar.countdown": "Contagem regressiva",
    "settings.bar.hijri": "Data hégira",
    "settings.bar.hijri.format.off": "Desativada",
    "settings.bar.hijri.format.full": "Completa (15 Shawwāl 1447)",
    "settings.bar.hijri.format.daymonth": "Dia + mês (15 Shawwāl)",
    "settings.bar.hijri.format.month": "Só o mês (Shawwāl)",
    "settings.bar.hijri.format.day": "Só o dia (15)",
    "settings.quit": "Sair",
    "picker.title": "Escolher mesquita",
    "picker.btn.search": "Pesquisar",
    "picker.btn.add": "Adicionar",
    "picker.btn.near": "Próximo",
    "picker.tab.favorites": "Favoritos",
    "picker.tab.search": "Pesquisar",
    "picker.tab.near": "Próximo",
    "picker.tab.url": "Adicionar por URL",
    "picker.placeholder.search": "Pesquisar cidade ou mesquita",
    "picker.placeholder.city": "Sua cidade",
    "settings.tab.mosque": "Mesquita",
    "settings.tab.appearance": "Aparência",
    "settings.tab.menu_bar": "Barra de menus",
    "settings.tab.sound": "Som",
    "settings.section.startup": "Inicialização",
    "settings.startup.open_at_login": "Abrir ao iniciar sessão",
    "tooltip.open_at_login_failed": "O macOS recusou o registro. Ative em Ajustes do Sistema → Geral → Itens de Início.",
    "picker.tooltip.remove_fav": "Remover dos favoritos",
    "picker.tooltip.saved": "Salvo nos favoritos",
    "picker.tooltip.add_fav": "Adicionar aos favoritos",
    "picker.tooltip.is_default": "Mesquita atual",
    "picker.tooltip.set_default": "Definir como padrão",
    "picker.status.set_default_prefix": "Padrão definida:",
    "picker.status.added_fav_prefix": "Adicionado aos favoritos:",
    "picker.status.removed_fav_prefix": "Removido dos favoritos:",
    "menu.adhkar": "Adhkār",
    "adhkar.morning_title": "Adhkār da Manhã",
    "adhkar.evening_title": "Adhkār da Tarde",
    "adhkar.play": "Reproduzir",
    "adhkar.pause": "Pausar",
    "adhkar.mute": "Silenciar",
    "adhkar.unmute": "Ativar som",
    "adhkar.stop": "Parar",
    "adhkar.next": "Dhikr seguinte",
    "adhkar.prev": "Dhikr anterior",
    "settings.section.adhkar": "Adhkār",
    "settings.adhkar.auto": "Recitar automaticamente os adhkār da manhã e da tarde",
    "main.tab.prayer_times": "Horários de Oração",
    "main.tab.adhkar": "Adhkār",
    "main.tab.adhan": "Adhān",
    "main.tab.settings": "Ajustes",
    "menu.main_window": "Abrir janela principal…",
    "adhkar.editor.coming_soon": "Editor de adhkār — na próxima versão",
    "adhkar.editor.title": "Coleções de Adhkār",
    "adhkar.editor.collections": "Coleções",
    "adhkar.editor.new_collection": "Nova coleção",
    "adhkar.editor.untitled": "Sem título",
    "adhkar.editor.items_in": "Itens em «%@»",
    "adhkar.editor.add_from_library": "Adicionar da biblioteca…",
    "adhkar.editor.add_custom": "Adicionar personalizado…",
    "adhkar.editor.no_collection_selected": "Selecione uma coleção ou crie uma nova.",
    "adhkar.editor.empty_collection": "Esta coleção está vazia. Adicione adhkār da biblioteca ou crie os seus.",
    "adhkar.editor.delete_collection": "Eliminar esta coleção?",
    "adhkar.editor.delete_collection_msg": "Esta ação não pode ser desfeita.",
    "adhkar.editor.delete_item": "Remover este dhikr?",
    "adhkar.editor.repeat": "Repetição",
    "adhkar.editor.virtue": "Virtude / Notas",
    "adhkar.editor.source": "Fonte",
    "adhkar.editor.arabic": "Texto árabe",
    "adhkar.editor.audio": "Áudio",
    "adhkar.editor.audio.choose": "Escolher áudio…",
    "adhkar.editor.audio.import": "Importar ficheiro…",
    "adhkar.editor.audio.none": "Nenhum",
    "adhkar.editor.schedule": "Agendamento",
    "adhkar.editor.schedule.manual": "Manual (sem auto-play)",
    "adhkar.editor.schedule.shuruq": "Ao nascer do sol (Shurūq)",
    "adhkar.editor.schedule.fajr": "Após Fajr",
    "adhkar.editor.schedule.dhuhr": "Após Dhuhr",
    "adhkar.editor.schedule.asr": "Após Asr",
    "adhkar.editor.schedule.maghrib": "Após Maghrib",
    "adhkar.editor.schedule.isha": "Após Ishā",
    "adhkar.editor.autoplay": "Reproduzir automaticamente no horário agendado",
    "adhkar.editor.save": "Guardar",
    "adhkar.editor.cancel": "Cancelar",
    "adhkar.editor.library_title": "Adicionar da biblioteca",
    "adhkar.editor.library_pick": "Escolha os adhkār a adicionar:",
    "adhkar.editor.library_add_selected": "Adicionar selecionados",
    "adhkar.editor.custom_title": "Adicionar dhikr personalizado",
    "adhkar.editor.custom_hint": "Digite ou cole o texto árabe, depois escolha o número de repetições e o áudio.",
    "adhkar.editor.move_up": "Mover para cima",
    "adhkar.editor.move_down": "Mover para baixo",
    "adhkar.editor.remove": "Remover",
    "adhkar.editor.play_preview": "Pré-visualizar áudio",
    "adhkar.import_audio": "Importar",
    "adhkar.editor.renamed": "Renomeado",
    "adhkar.editor.count_times": "%d vezes"
  },
  "ur": {
    "col.prayer": "نماز",
    "col.adhan": "اذان",
    "col.iqama": "اقامہ",
    "prayer.fajr": "فجر",
    "prayer.shuruq": "طلوع آفتاب",
    "prayer.dhuhr": "ظہر",
    "prayer.asr": "عصر",
    "prayer.maghrib": "مغرب",
    "prayer.isha": "عشاء",
    "label.jumua": "جمعہ",
    "label.next_prayer": "اگلی نماز",
    "tooltip.refresh": "تازہ کریں",
    "tooltip.language": "زبان تبدیل کریں",
    "tooltip.theme": "تھیم",
    "menu.theme.header.appearance": "ظاہری شکل",
    "menu.theme.appearance.system": "سسٹم",
    "menu.theme.appearance.light": "ہلکا",
    "menu.theme.appearance.dark": "گہرا",
    "menu.theme.header.accent": "لہجے کا رنگ",
    "menu.theme.accent.green": "سبز",
    "menu.theme.accent.blue": "نیلا",
    "menu.theme.accent.purple": "جامنی",
    "menu.theme.accent.orange": "نارنجی",
    "menu.theme.accent.red": "سرخ",
    "menu.theme.accent.teal": "ہلکا سبز نیلا",
    "menu.theme.header.material": "پس منظر",
    "menu.theme.material.opaque": "مبہم",
    "menu.theme.material.glass": "مائع شیشہ",
    "tooltip.change": "مسجد تبدیل کریں",
    "tooltip.settings": "ترتیبات",
    "tooltip.back": "واپس",
    "tooltip.test_adhan": "اذان ٹیسٹ",
    "tooltip.stop_adhan": "اذان روکیں",
    "mosque.default": "مسجد",
    "menu.open": "صلاۃ ٹائم کھولیں",
    "menu.refresh": "تازہ کریں",
    "menu.choose": "مسجد منتخب کریں…",
    "menu.settings": "ترتیبات…",
    "menu.favorites": "پسندیدہ",
    "menu.quit": "بند کریں",
    "settings.title": "ترتیبات",
    "settings.section.language": "زبان",
    "settings.section.appearance": "شکل",
    "settings.section.accent": "ایکسنٹ رنگ",
    "settings.section.material": "میٹیریل",
    "settings.section.adhan": "اذان",
    "settings.section.notifications": "اطلاعات",
    "settings.section.mosque": "مسجد",
    "settings.appearance.system": "سسٹم",
    "settings.appearance.light": "روشن",
    "settings.appearance.dark": "گہرا",
    "settings.adhan.play": "اذان چلائیں",
    "settings.adhan.sound": "آواز",
    "settings.adhan.output": "آؤٹ پٹ",
    "settings.adhan.output.default": "سسٹم ڈیفالٹ",
    "settings.notif.show": "اطلاعات دکھائیں",
    "settings.mosque.currently": "فی الحال",
    "settings.mosque.none": "منتخب نہیں",
    "settings.mosque.change": "مسجد تبدیل کریں",
    "settings.section.time_format": "وقت کی شکل",
    "settings.time_format.24h": "۲۴ گھنٹے",
    "settings.time_format.12h": "۱۲ گھنٹے",
    "settings.section.menu_bar": "مینو بار",
    "settings.bar.icon": "آئیکن",
    "settings.bar.time": "مقررہ وقت",
    "settings.bar.countdown": "الٹی گنتی",
    "settings.bar.hijri": "ہجری تاریخ",
    "settings.bar.hijri.format.off": "بند",
    "settings.bar.hijri.format.full": "مکمل (15 Shawwāl 1447)",
    "settings.bar.hijri.format.daymonth": "دن + مہینہ (15 Shawwāl)",
    "settings.bar.hijri.format.month": "صرف مہینہ (Shawwāl)",
    "settings.bar.hijri.format.day": "صرف دن (15)",
    "settings.quit": "بند کریں",
    "picker.title": "مسجد منتخب کریں",
    "picker.btn.search": "تلاش",
    "picker.btn.add": "شامل کریں",
    "picker.btn.near": "قریبی",
    "picker.tab.favorites": "پسندیدہ",
    "picker.tab.search": "تلاش",
    "picker.tab.near": "قریبی",
    "picker.tab.url": "URL سے شامل کریں",
    "picker.placeholder.search": "شہر یا مسجد تلاش کریں",
    "picker.placeholder.city": "آپ کا شہر",
    "settings.tab.mosque": "مسجد",
    "settings.tab.appearance": "ظاہری شکل",
    "settings.tab.menu_bar": "مینو بار",
    "settings.tab.sound": "آواز",
    "settings.section.startup": "آغاز",
    "settings.startup.open_at_login": "لاگ اِن پر کھولیں",
    "tooltip.open_at_login_failed": "macOS نے رجسٹریشن مسترد کر دی۔ سسٹم سیٹنگز → عمومی → لاگ اِن آئٹمز سے فعال کریں۔",
    "picker.tooltip.remove_fav": "پسندیدہ سے نکالیں",
    "picker.tooltip.saved": "پسندیدہ میں محفوظ",
    "picker.tooltip.add_fav": "پسندیدہ میں شامل کریں",
    "picker.tooltip.is_default": "موجودہ مسجد",
    "picker.tooltip.set_default": "ڈیفالٹ مقرر کریں",
    "picker.status.set_default_prefix": "ڈیفالٹ مقرر:",
    "picker.status.added_fav_prefix": "پسندیدہ میں شامل:",
    "picker.status.removed_fav_prefix": "پسندیدہ سے خارج:",
    "menu.adhkar": "اذکار",
    "adhkar.morning_title": "اذکارِ صباح",
    "adhkar.evening_title": "اذکارِ مساء",
    "adhkar.play": "چلائیں",
    "adhkar.pause": "روکیں",
    "adhkar.mute": "آواز بند",
    "adhkar.unmute": "آواز چالو",
    "adhkar.stop": "بند کریں",
    "adhkar.next": "اگلا ذکر",
    "adhkar.prev": "پچھلا ذکر",
    "settings.section.adhkar": "اذکار",
    "settings.adhkar.auto": "اذکارِ صباح و مساء خودکار تلاوت",
    "main.tab.prayer_times": "نماز کے اوقات",
    "main.tab.adhkar": "اذکار",
    "main.tab.adhan": "اذان",
    "main.tab.settings": "ترتیبات",
    "menu.main_window": "مرکزی ونڈو کھولیں…",
    "adhkar.editor.coming_soon": "اذکار ایڈیٹر — اگلے ورژن میں",
    "adhkar.editor.title": "اذکار کے مجموعے",
    "adhkar.editor.collections": "مجموعے",
    "adhkar.editor.new_collection": "نیا مجموعہ",
    "adhkar.editor.untitled": "بے عنوان",
    "adhkar.editor.items_in": "”%@“ میں اشیاء",
    "adhkar.editor.add_from_library": "لائبریری سے شامل کریں…",
    "adhkar.editor.add_custom": "اپنا ذکر شامل کریں…",
    "adhkar.editor.no_collection_selected": "ایک مجموعہ منتخب کریں یا نیا بنائیں۔",
    "adhkar.editor.empty_collection": "یہ مجموعہ خالی ہے۔ لائبریری سے اذکار شامل کریں یا اپنے بنائیں۔",
    "adhkar.editor.delete_collection": "یہ مجموعہ حذف کریں؟",
    "adhkar.editor.delete_collection_msg": "اس عمل کو واپس نہیں کیا جا سکتا۔",
    "adhkar.editor.delete_item": "یہ ذکر ہٹائیں؟",
    "adhkar.editor.repeat": "تکرار",
    "adhkar.editor.virtue": "فضیلت / نوٹس",
    "adhkar.editor.source": "مآخذ",
    "adhkar.editor.arabic": "عربی متن",
    "adhkar.editor.audio": "آڈیو",
    "adhkar.editor.audio.choose": "آڈیو منتخب کریں…",
    "adhkar.editor.audio.import": "فائل درآمد کریں…",
    "adhkar.editor.audio.none": "کوئی نہیں",
    "adhkar.editor.schedule": "شیڈول",
    "adhkar.editor.schedule.manual": "دستی (خودکار نہیں)",
    "adhkar.editor.schedule.shuruq": "طلوع آفتاب پر",
    "adhkar.editor.schedule.fajr": "فجر کے بعد",
    "adhkar.editor.schedule.dhuhr": "ظہر کے بعد",
    "adhkar.editor.schedule.asr": "عصر کے بعد",
    "adhkar.editor.schedule.maghrib": "مغرب کے بعد",
    "adhkar.editor.schedule.isha": "عشاء کے بعد",
    "adhkar.editor.autoplay": "مقررہ وقت پر خودکار چلائیں",
    "adhkar.editor.save": "محفوظ کریں",
    "adhkar.editor.cancel": "منسوخ",
    "adhkar.editor.library_title": "لائبریری سے شامل کریں",
    "adhkar.editor.library_pick": "شامل کرنے کے لیے اذکار منتخب کریں:",
    "adhkar.editor.library_add_selected": "منتخب شدہ شامل کریں",
    "adhkar.editor.custom_title": "اپنا ذکر شامل کریں",
    "adhkar.editor.custom_hint": "عربی متن ٹائپ یا پیسٹ کریں، پھر تکرار اور آڈیو منتخب کریں۔",
    "adhkar.editor.move_up": "اوپر کریں",
    "adhkar.editor.move_down": "نیچے کریں",
    "adhkar.editor.remove": "ہٹائیں",
    "adhkar.editor.play_preview": "آڈیو پیش نظارہ",
    "adhkar.import_audio": "درآمد",
    "adhkar.editor.renamed": "نام بدلا گیا",
    "adhkar.editor.count_times": "%d بار"
  }
}
JSON_EOF

# ---------- Info.plist ------------------------------------------------------
cp Info.plist "$CONTENTS/Info.plist"

# ---------- Code signing ---------------------------------------------------
# Ad-hoc signature so Gatekeeper / LaunchServices are happy with the bundle.
echo "Signing app (ad-hoc)..."
codesign --force --sign - --timestamp=none \
    --identifier com.salattime.app \
    "$APP_DIR" \
    || echo "  (app sign failed — try: codesign --force --sign - \"$APP_DIR\")"

# Nudge Finder's icon cache
touch "$APP_DIR"

echo ""
echo "Built: $(pwd)/$APP_DIR"
